# Generated by Django 6.0.5 on 2026-06-17 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('monster', 'Monster'), ('character', 'Character'), ('projectile', 'Projectile'), ('relic', 'Relic'), ('battle_artifact', 'Battle artifact')], max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('store', 'Store')], default='public', max_length=10)),
                ('price', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=160)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('default_scale', models.FloatField(default=1.0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='AssetSprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='assets/sprites/')),
                ('frame_width', models.PositiveIntegerField(default=0)),
                ('frame_height', models.PositiveIntegerField(default=0)),
                ('columns', models.PositiveIntegerField(default=1)),
                ('rows', models.PositiveIntegerField(default=1)),
                ('frame_count', models.PositiveIntegerField(default=1)),
                ('fps', models.PositiveIntegerField(default=12)),
                ('loops', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprites', to='assets.asset')),
            ],
            options={
                'ordering': ['asset_id', 'action'],
            },
        ),
        migrations.CreateModel(
            name='RelicAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_box', models.CharField(blank=True, max_length=80)),
                ('interactive_viewbox', models.JSONField(blank=True, default=dict)),
                ('landing_viewbox', models.JSONField(blank=True, default=dict)),
                ('svg_sanitized', models.BooleanField(default=False)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relic', to='assets.asset')),
            ],
            options={
                'ordering': ['asset__slug'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['kind', 'is_published'], name='assets_asse_kind_671022_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetsprite',
            constraint=models.UniqueConstraint(fields=('asset', 'action'), name='unique_action_per_asset'),
        ),
    ]
