# Generated by Django 6.0.5 on 2026-06-13 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='kind',
            field=models.CharField(choices=[('monster', 'Monster'), ('character', 'Character'), ('projectile', 'Projectile'), ('tower_piece', 'Tower piece'), ('tower_artifact', 'Tower artifact')], max_length=20),
        ),
        migrations.CreateModel(
            name='TowerPieceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(choices=[('spire', 'Spire'), ('landing', 'Landing'), ('door', 'Door'), ('adventure_section', 'Adventure section'), ('challenge_section', 'Challenge section'), ('tome', 'Tome')], max_length=32)),
                ('view_box', models.CharField(blank=True, max_length=80)),
                ('anchors', models.JSONField(blank=True, default=dict)),
                ('bounds', models.JSONField(blank=True, default=dict)),
                ('interaction_zones', models.JSONField(blank=True, default=dict)),
                ('state_variants', models.JSONField(blank=True, default=dict)),
                ('svg_sanitized', models.BooleanField(default=False)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tower_piece', to='assets.asset')),
            ],
            options={
                'ordering': ['piece_type', 'asset__slug'],
                'indexes': [models.Index(fields=['piece_type'], name='assets_towe_piece_t_47aa13_idx')],
            },
        ),
    ]
