# Generated by Django 6.0.5 on 2026-06-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_kind_towerpieceasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
