# Generated by Django 6.0.5 on 2026-06-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='kind',
            field=models.CharField(choices=[('monster', 'Monster'), ('character', 'Character'), ('projectile', 'Projectile'), ('tower_piece', 'Tower piece'), ('tower_artifact', 'Tower artifact'), ('battle_artifact', 'Battle artifact')], max_length=20),
        ),
    ]
