# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_alter_asset_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="towerpieceasset",
            name="piece_type",
            field=models.CharField(
                choices=[
                    ("spire", "Spire"),
                    ("window_section", "Window section"),
                    ("landing", "Landing"),
                    ("door", "Door"),
                    ("adventure_section", "Adventure section"),
                    ("challenge_section", "Challenge section"),
                    ("tome", "Tome"),
                ],
                max_length=32,
            ),
        ),
    ]
