# Generated by Codex on 2026-06-15

from django.db import migrations, models


OLD_TO_NEW = {
    "spire": "crown",
    "window_section": "section",
    "adventure_section": "section",
    "challenge_section": "section",
}


def forwards(apps, schema_editor):
    TowerPieceAsset = apps.get_model("assets", "TowerPieceAsset")
    for old, new in OLD_TO_NEW.items():
        TowerPieceAsset.objects.filter(piece_type=old).update(piece_type=new)
    TowerPieceAsset.objects.filter(piece_type__in=["door", "tome"]).delete()


def backwards(apps, schema_editor):
    TowerPieceAsset = apps.get_model("assets", "TowerPieceAsset")
    TowerPieceAsset.objects.filter(piece_type="crown").update(piece_type="spire")
    TowerPieceAsset.objects.filter(piece_type="section").update(piece_type="window_section")


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_alter_towerpieceasset_piece_type"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="towerpieceasset",
            name="piece_type",
            field=models.CharField(
                choices=[
                    ("crown", "Crown"),
                    ("section", "Section"),
                    ("landing", "Landing"),
                ],
                max_length=32,
            ),
        ),
    ]
