# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_generalize_tower_piece_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="towerpieceasset",
            name="piece_type",
            field=models.CharField(
                choices=[
                    ("crown", "Crown"),
                    ("base", "Base"),
                    ("section", "Section"),
                    ("landing", "Landing"),
                ],
                max_length=32,
            ),
        ),
    ]
