# Generated by Django 6.0.5 on 2026-06-13 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_asset_kind_towerpieceasset'),
        ('authoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('store', 'Store')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tower_designs', to=settings.AUTH_USER_MODEL)),
                ('source_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixes', to='towers.towerdesign')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TowerPieceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('transform', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('parent_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='towers.towerpieceinstance')),
                ('piece_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset')),
                ('tower_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='towers.towerdesign')),
            ],
            options={
                'ordering': ['tower_design_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TowerContentBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tower_bindings', to='authoring.contentdefinition')),
                ('piece_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_binding', to='towers.towerpieceinstance')),
            ],
            options={
                'ordering': ['piece_instance__tower_design_id', 'piece_instance__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('scale', models.FloatField(default=1)),
                ('rotation', models.FloatField(default=0)),
                ('anchor', models.CharField(blank=True, max_length=80)),
                ('z_index', models.IntegerField(default=0)),
                ('artifact_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset')),
                ('tower_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_placements', to='towers.towerdesign')),
                ('target_piece_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_placements', to='towers.towerpieceinstance')),
            ],
            options={
                'ordering': ['tower_design_id', 'z_index', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='towerdesign',
            index=models.Index(fields=['owner', 'status'], name='tower_design_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='towerdesign',
            index=models.Index(fields=['visibility', 'status'], name='tower_design_vis_idx'),
        ),
        migrations.AddConstraint(
            model_name='towerdesign',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_tower_design_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='towerdesign',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner',), name='unique_active_tower_design_per_owner'),
        ),
        migrations.AddIndex(
            model_name='towerpieceinstance',
            index=models.Index(fields=['tower_design', 'sort_order'], name='tower_piece_design_order_idx'),
        ),
    ]
