# Generated by Django 6.0.5 on 2026-06-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerdesign',
            name='origin',
            field=models.CharField(choices=[('personal', 'Personal'), ('official_fork', 'Official fork')], default='personal', max_length=16),
        ),
    ]
