# Generated by Django 6.0.5 on 2026-06-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0002_towerdesign_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerpieceinstance',
            name='storey_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
