# Generated by Codex on 2026-06-15

import django.db.models.deletion
from django.db import migrations, models


OLD_TO_NEW_PIECES = {
    "spire": "crown",
    "window_section": "section",
    "adventure_section": "section",
    "challenge_section": "section",
}


def forwards(apps, schema_editor):
    TowerPieceInstance = apps.get_model("towers", "TowerPieceInstance")

    for old, new in OLD_TO_NEW_PIECES.items():
        TowerPieceInstance.objects.filter(piece_type=old).update(piece_type=new)
    TowerPieceInstance.objects.filter(piece_type__in=["door", "tome"]).delete()


def backwards(apps, schema_editor):
    TowerPieceInstance = apps.get_model("towers", "TowerPieceInstance")
    TowerPieceInstance.objects.filter(piece_type="crown").update(piece_type="spire")
    TowerPieceInstance.objects.filter(piece_type="section").update(piece_type="window_section")


class Migration(migrations.Migration):

    dependencies = [
        ("authoring", "0001_initial"),
        ("towers", "0003_towerpieceinstance_storey_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifactplacement",
            name="content_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tower_artifact_placements",
                to="authoring.contentdefinition",
            ),
        ),
        migrations.AddField(
            model_name="artifactplacement",
            name="height",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="artifactplacement",
            name="role",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("adventure", "Adventure"),
                    ("challenge", "Challenge"),
                    ("tome", "Tome"),
                ],
                default="normal",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="artifactplacement",
            name="width",
            field=models.FloatField(default=0),
        ),
        migrations.RunPython(forwards, backwards),
    ]
