# Generated by Django 6.0.5 on 2026-06-17 06:39

import authoring.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedContentRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_signature', models.CharField(max_length=64)),
                ('compiled_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['content_definition_id'],
            },
        ),
        migrations.CreateModel(
            name='AuthoringChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('chest_rewards', models.JSONField(blank=True, default=authoring.models._default_chest_rewards)),
                ('mob_roster', models.JSONField(blank=True, default=list)),
                ('boss_roster', models.JSONField(blank=True, default=list)),
                ('pass_bar_fraction', models.FloatField(default=0.6)),
                ('battle_stage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoring_chapters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('adventure', 'Adventure'), ('challenge', 'Challenge'), ('tome', 'Tome')], max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('store', 'Store')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('testable', 'Testable'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('command_family', models.CharField(blank=True, max_length=80)),
                ('difficulty', models.CharField(blank=True, max_length=12)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='authoring.authoringchapter')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_definitions', to=settings.AUTH_USER_MODEL)),
                ('source_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixes', to='authoring.contentdefinition')),
            ],
            options={
                'ordering': ['kind', 'title', 'id'],
            },
        ),
    ]
