# Generated by Django 6.0.5 on 2026-06-13 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0008_rename_quest_to_level'),
        ('challenges', '0007_rename_quest_to_level'),
        ('curriculum', '0006_storey_boss_roster_storey_mob_roster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('adventure', 'Adventure'), ('challenge', 'Challenge'), ('tome', 'Tome')], max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('store', 'Store')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('testable', 'Testable'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('command_family', models.CharField(blank=True, max_length=80)),
                ('difficulty', models.CharField(blank=True, max_length=12)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_definitions', to=settings.AUTH_USER_MODEL)),
                ('source_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixes', to='authoring.contentdefinition')),
            ],
            options={
                'ordering': ['kind', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublishedContentRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_signature', models.CharField(max_length=64)),
                ('compiled_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.challenge')),
                ('command_adventure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventures.commandadventure')),
                ('content_definition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime', to='authoring.contentdefinition')),
                ('storey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.storey')),
                ('tome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.tome')),
            ],
            options={
                'ordering': ['content_definition_id'],
            },
        ),
        migrations.AddIndex(
            model_name='contentdefinition',
            index=models.Index(fields=['owner', 'kind', 'status'], name='auth_content_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdefinition',
            index=models.Index(fields=['visibility', 'status'], name='auth_content_vis_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentdefinition',
            constraint=models.UniqueConstraint(fields=('owner', 'kind', 'slug'), name='unique_content_slug_per_owner_kind'),
        ),
    ]
