# Generated by Django 6.0.7 on 2026-08-25 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0002_initial'),
        ('authoring', '0001_initial'),
        ('challenges', '0001_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdefinition',
            name='official_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_content_definitions', to='curriculum.chapter'),
        ),
        migrations.AddField(
            model_name='contentdefinition',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_definitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentdefinition',
            name='source_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixes', to='authoring.contentdefinition'),
        ),
        migrations.AddField(
            model_name='publishedcontentruntime',
            name='adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventures.adventurelevel'),
        ),
        migrations.AddField(
            model_name='publishedcontentruntime',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.challengelevel'),
        ),
        migrations.AddField(
            model_name='publishedcontentruntime',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.chapter'),
        ),
        migrations.AddField(
            model_name='publishedcontentruntime',
            name='content_definition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime', to='authoring.contentdefinition'),
        ),
        migrations.AddField(
            model_name='publishedcontentruntime',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.chapterlesson'),
        ),
        migrations.AddConstraint(
            model_name='authoringchapter',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_authoring_chapter_slug_per_owner'),
        ),
        migrations.AddIndex(
            model_name='contentdefinition',
            index=models.Index(fields=['owner', 'kind', 'status'], name='auth_content_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdefinition',
            index=models.Index(fields=['visibility', 'status'], name='auth_content_vis_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentdefinition',
            constraint=models.UniqueConstraint(fields=('owner', 'kind', 'slug'), name='unique_content_slug_per_owner_kind'),
        ),
        migrations.AddConstraint(
            model_name='contentdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('kind', 'slug'), name='unique_system_content_slug_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='contentdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['private', 'public'])), name='authoring_content_valid_visibility'),
        ),
        migrations.AddConstraint(
            model_name='contentdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('chapter__isnull', True), ('official_chapter__isnull', True), _connector='OR'), name='authoring_content_one_chapter_type'),
        ),
        migrations.AddConstraint(
            model_name='publishedcontentruntime',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adventure__isnull', False), ('challenge__isnull', True), ('lesson__isnull', True)), models.Q(('adventure__isnull', True), ('challenge__isnull', False), ('lesson__isnull', True)), models.Q(('adventure__isnull', True), ('challenge__isnull', True), ('lesson__isnull', False)), _connector='OR'), name='published_runtime_exactly_one_target'),
        ),
    ]
