# Generated by Django 6.0.5 on 2026-06-17 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0002_initial'),
        ('authoring', '0001_initial'),
        ('challenges', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedcontentruntime',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.challenge'),
        ),
        migrations.AddField(
            model_name='publishedcontentruntime',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.chapter'),
        ),
        migrations.AddField(
            model_name='publishedcontentruntime',
            name='command_adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventures.commandadventure'),
        ),
        migrations.AddField(
            model_name='publishedcontentruntime',
            name='content_definition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime', to='authoring.contentdefinition'),
        ),
        migrations.AddField(
            model_name='publishedcontentruntime',
            name='tome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.tome'),
        ),
        migrations.AddConstraint(
            model_name='authoringchapter',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_authoring_chapter_slug_per_owner'),
        ),
        migrations.AddIndex(
            model_name='contentdefinition',
            index=models.Index(fields=['owner', 'kind', 'status'], name='auth_content_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdefinition',
            index=models.Index(fields=['visibility', 'status'], name='auth_content_vis_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentdefinition',
            constraint=models.UniqueConstraint(fields=('owner', 'kind', 'slug'), name='unique_content_slug_per_owner_kind'),
        ),
    ]
