# Generated by Django 6.0.5 on 2026-06-14 02:09

import authoring.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoringStorey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('chest_rewards', models.JSONField(blank=True, default=authoring.models._default_chest_rewards)),
                ('mob_roster', models.JSONField(blank=True, default=list)),
                ('boss_roster', models.JSONField(blank=True, default=list)),
                ('pass_bar_fraction', models.FloatField(default=0.6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoring_storeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contentdefinition',
            name='storey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='authoring.authoringstorey'),
        ),
        migrations.AddConstraint(
            model_name='authoringstorey',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_authoring_storey_slug_per_owner'),
        ),
    ]
