# Generated by Django 6.0.5 on 2026-06-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0002_authoringstorey_contentdefinition_storey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoringstorey',
            name='battle_stage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
