# Generated by Django 6.0.5 on 2026-07-18 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_remove_skillmastery_skillmastery_plyr_form_idx_and_more'),
        ('authoring', '0002_initial'),
        ('challenges', '0002_remove_unused_level_brief'),
        ('curriculum', '0002_remove_unused_narrative_briefs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contentdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('kind', 'slug'), name='unique_system_content_slug_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='publishedcontentruntime',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adventure__isnull', False), ('challenge__isnull', True), ('lesson__isnull', True)), models.Q(('adventure__isnull', True), ('challenge__isnull', False), ('lesson__isnull', True)), models.Q(('adventure__isnull', True), ('challenge__isnull', True), ('lesson__isnull', False)), _connector='OR'), name='published_runtime_exactly_one_target'),
        ),
    ]
