# Generated by Django 6.0.5 on 2026-07-19 17:11

from django.conf import settings
from django.db import migrations, models


def make_store_content_public(apps, schema_editor):
    ContentDefinition = apps.get_model("authoring", "ContentDefinition")
    ContentDefinition.objects.using(schema_editor.connection.alias).filter(
        visibility="store"
    ).update(visibility="public")


class Migration(migrations.Migration):
    # Commit data repairs before PostgreSQL installs constraints. Keeping the
    # UPDATE and ALTER TABLE in one transaction leaves pending FK trigger events.
    atomic = False

    dependencies = [
        ("authoring", "0003_contentdefinition_unique_system_content_slug_per_kind_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            make_store_content_public,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="contentdefinition",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")],
                default="private",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="contentdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("visibility__in", ["private", "public"])),
                name="authoring_content_valid_visibility",
            ),
        ),
    ]
