# Generated by Django 6.0.7 on 2026-07-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLoadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_companion_slug', models.SlugField(blank=True, default=None, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loadout', to='players.player')),
            ],
            options={
                'ordering': ['player_id'],
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('story', 'Story'), ('companion', 'Companion')], max_length=16)),
                ('slug', models.SlugField(max_length=64)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='players.player')),
            ],
            options={
                'ordering': ['-granted_at', '-id'],
                'indexes': [models.Index(fields=['player', 'kind'], name='entitlement_player_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'kind', 'slug'), name='unique_shop_entitlement')],
            },
        ),
    ]
