# Generated by Django 6.0.5 on 2026-07-18 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_playerpreferences_theme_mode'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entitlement',
            name='entitlement_player_kind_idx',
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='player',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='players.player'),
        ),
    ]
