# Generated by Django 6.0.5 on 2026-05-18 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('is_orientation', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('kind', models.CharField(choices=[('orientation', 'Orientation'), ('content', 'Content'), ('scenario', 'Scenario-bearing')], max_length=24)),
                ('overview_html', models.TextField()),
                ('scoped_css', models.TextField(blank=True)),
                ('interaction_steps', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.learningunit')),
            ],
            options={
                'ordering': ['unit__sort_order', 'sort_order'],
                'unique_together': {('unit', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='OrientationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('highest_step_seen', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
