# Generated by Django 6.0.7 on 2026-07-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authoring', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('narrative', models.TextField(blank=True)),
                ('brief', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_levels', to='curriculum.chapter')),
                ('command_forms', models.ManyToManyField(blank=True, related_name='challenge_levels', to='curriculum.commandform')),
                ('source_content_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_challenge_levels', to='authoring.contentdefinition')),
            ],
            options={
                'ordering': ['chapter__sort_order', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=12)),
                ('story', models.TextField(blank=True)),
                ('task', models.TextField(blank=True)),
                ('min_counted_commands', models.PositiveIntegerField(default=1)),
                ('max_counted_commands', models.PositiveIntegerField(default=4)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('objective_checks', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('challenge_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='challenges.challengelevel')),
            ],
            options={
                'ordering': ['challenge_level__chapter__sort_order', 'challenge_level__sort_order', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeTrialVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=80)),
                ('initial_state', models.JSONField(default=dict)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('target_state', models.JSONField(blank=True, default=dict)),
                ('solution_commands', models.JSONField(blank=True, default=list)),
                ('case_id', models.CharField(blank=True, max_length=160)),
                ('semantic_key', models.CharField(blank=True, max_length=240)),
                ('parameter_context', models.JSONField(blank=True, default=dict)),
                ('scenario_context', models.JSONField(blank=True, default=dict)),
                ('scaffold_policy', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='challenges.challengetrial')),
            ],
            options={
                'ordering': ['trial_id', 'semantic_key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_entry_point', models.CharField(max_length=40)),
                ('is_replay', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='started', max_length=16)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('min_counted_commands', models.PositiveIntegerField(default=1)),
                ('max_counted_commands', models.PositiveIntegerField(default=4)),
                ('repository_state', models.JSONField(default=dict)),
                ('counted_action_total', models.PositiveIntegerField(default=0)),
                ('non_counted_diagnostic_total', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('retry_index', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, max_length=160)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_runs', to='players.player')),
                ('prior_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_runs', to='challenges.challengerun')),
                ('challenge_trial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenges.challengetrial')),
                ('selected_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenge_runs', to='challenges.challengetrialvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='challengelevel',
            index=models.Index(fields=['chapter', 'sort_order'], name='chal_level_chapter_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengelevel',
            constraint=models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_challenge_level_chapter_slug'),
        ),
        migrations.AddConstraint(
            model_name='challengetrial',
            constraint=models.UniqueConstraint(fields=('challenge_level', 'difficulty'), name='unique_challenge_trial_difficulty'),
        ),
        migrations.AddConstraint(
            model_name='challengetrialvariant',
            constraint=models.UniqueConstraint(fields=('trial', 'slug'), name='unique_challenge_trial_variant_slug'),
        ),
        migrations.AddIndex(
            model_name='challengerun',
            index=models.Index(fields=['player', 'is_replay', 'status'], name='chal_plyr_replay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='challengerun',
            index=models.Index(fields=['player', 'challenge_trial', '-id'], name='chal_plyr_trial_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengerun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'started')), fields=('player', 'challenge_trial'), name='unique_active_challenge_run'),
        ),
    ]
