# Generated by Django 6.0.5 on 2026-06-17 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authoring', '0001_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('narrative', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='curriculum.chapter')),
                ('source_content_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_challenges', to='authoring.contentdefinition')),
            ],
            options={
                'ordering': ['chapter__sort_order', 'sort_order', 'title'],
                'unique_together': {('chapter', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=12)),
                ('required_successful_attempts', models.PositiveIntegerField(default=2)),
                ('min_counted_commands', models.PositiveIntegerField(default=1)),
                ('max_counted_commands', models.PositiveIntegerField(default=8)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('scenario_context', models.JSONField(blank=True, default=dict)),
                ('boss_spec', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_levels', to='challenges.challenge')),
            ],
            options={
                'ordering': ['challenge__sort_order', 'difficulty'],
                'unique_together': {('challenge', 'difficulty')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=80)),
                ('initial_state', models.JSONField(default=dict)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('target_state', models.JSONField(blank=True, default=dict)),
                ('solution_commands', models.JSONField(blank=True, default=list)),
                ('case_id', models.CharField(blank=True, max_length=160)),
                ('semantic_key', models.CharField(blank=True, max_length=240)),
                ('parameter_context', models.JSONField(blank=True, default=dict)),
                ('scenario_context', models.JSONField(blank=True, default=dict)),
                ('hint_set', models.JSONField(blank=True, default=list)),
                ('scaffold_policy', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('command_budget', models.JSONField(blank=True, default=dict)),
                ('challenge_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_variants', to='challenges.challengelevel')),
            ],
            options={
                'ordering': ['challenge_level_id', 'semantic_key', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChallengeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_entry_point', models.CharField(max_length=40)),
                ('mode', models.CharField(choices=[('primary', 'Primary'), ('review', 'Review')], default='primary', max_length=16)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='started', max_length=16)),
                ('difficulty', models.CharField(blank=True, max_length=12)),
                ('rta_eligible', models.BooleanField(default=False)),
                ('rta_success', models.BooleanField(default=False)),
                ('changed_variant', models.BooleanField(default=False)),
                ('looped_variant', models.BooleanField(default=False)),
                ('command_budget_snapshot', models.JSONField(default=dict)),
                ('repository_state', models.JSONField(default=dict)),
                ('battle_state', models.JSONField(blank=True, default=dict)),
                ('counted_action_total', models.PositiveIntegerField(default=0)),
                ('non_counted_diagnostic_total', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('retry_index', models.PositiveIntegerField(default=0)),
                ('first_attempt_star_eligible', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=160)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenges.challenge')),
                ('challenge_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenges.challengelevel')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.chapter')),
                ('prior_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_runs', to='challenges.challengerun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('challenge_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenges.challengevariant')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'mode', 'status'], name='challenge_user_mode_status_idx'), models.Index(fields=['user', 'challenge_level', '-id'], name='chal_user_level_latest_idx')],
            },
        ),
    ]
