# Generated by Django 6.0.5 on 2026-06-10 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('curriculum', '0002_storey_chest_rewards'),
        ('progress', '0002_wallet_cointransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChallengeLevel',
            new_name='ChallengeQuest',
        ),
        migrations.AlterModelOptions(
            name='challengevariant',
            options={'ordering': ['challenge_quest_id', 'semantic_key', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='challengerun',
            name='chal_user_level_latest_idx',
        ),
        migrations.RenameField(
            model_name='challengerun',
            old_name='challenge_level',
            new_name='challenge_quest',
        ),
        migrations.RenameField(
            model_name='challengevariant',
            old_name='challenge_level',
            new_name='challenge_quest',
        ),
        migrations.AddIndex(
            model_name='challengerun',
            index=models.Index(fields=['user', 'challenge_quest', '-id'], name='chal_user_level_latest_idx'),
        ),
    ]
