# Generated by Django 6.0.5 on 2026-09-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challengetrialvariant_solution_workspace_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengetrialvariant',
            name='scaffold_policy',
        ),
    ]
