# Generated by Django 6.0.5 on 2026-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_remove_unused_level_brief'),
        ('players', '0002_remove_playerpreferences_theme_mode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='challengerun',
            constraint=models.CheckConstraint(condition=models.Q(('min_counted_commands__gte', 1), ('max_counted_commands__gte', models.F('min_counted_commands'))), name='challenge_run_valid_command_budget'),
        ),
        migrations.AddConstraint(
            model_name='challengerun',
            constraint=models.CheckConstraint(condition=models.Q(('stars__lte', 3)), name='challenge_run_stars_lte_3'),
        ),
        migrations.AddConstraint(
            model_name='challengetrial',
            constraint=models.CheckConstraint(condition=models.Q(('min_counted_commands__gte', 1), ('max_counted_commands__gte', models.F('min_counted_commands'))), name='challenge_trial_valid_command_budget'),
        ),
    ]
