# Generated by Django 6.0.7 on 2026-07-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challengerun_challenge_run_valid_command_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengetrialvariant',
            name='slug',
            field=models.SlugField(max_length=160),
        ),
    ]
