# Generated by Django 6.0.5 on 2026-06-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_rename_module_storey_and_more'),
        ('curriculum', '0004_alter_commandform_options_alter_commandskill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['storey__sort_order', 'sort_order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='challengequest',
            options={'ordering': ['challenge__sort_order', 'difficulty']},
        ),
        migrations.AlterField(
            model_name='challenge',
            name='storey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='curriculum.storey'),
        ),
        migrations.AlterField(
            model_name='challengequest',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_quests', to='challenges.challenge'),
        ),
        migrations.AlterField(
            model_name='challengerun',
            name='prior_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_runs', to='challenges.challengerun'),
        ),
        migrations.AlterField(
            model_name='challengevariant',
            name='challenge_quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_variants', to='challenges.challengequest'),
        ),
    ]
