# Generated by Django 6.0.5 on 2026-06-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_challenge_options_alter_challengequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequest',
            name='boss_spec',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='challengerun',
            name='battle_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='challengevariant',
            name='sabotage_script',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
