# Generated by Django 6.0.5 on 2026-06-13 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challengequest_boss_spec_challengerun_battle_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengevariant',
            name='sabotage_script',
        ),
    ]
