# Generated by Django 6.0.7 on 2026-07-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0002_initial'),
        ('challenges', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_completed_on', models.DateField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_practice_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='AdventureLevelCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('counted_action_total', models.PositiveIntegerField(default=0)),
                ('adventure_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='adventures.adventurelevel')),
                ('adventure_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion', to='adventures.adventurerun')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'adventure_level'), name='unique_adventure_level_completion')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeLevelCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('challenge_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='challenges.challengelevel')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'challenge_level'), name='unique_challenge_level_completion')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeTrialCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('counted_action_total', models.PositiveIntegerField(default=0)),
                ('challenge_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion', to='challenges.challengerun')),
                ('challenge_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='challenges.challengetrial')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'challenge_trial'), name='unique_challenge_trial_completion')],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=64)),
                ('award_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='players.player')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('player', 'award_key'), name='unique_award_per_player')],
            },
        ),
    ]
