# Generated by Django 6.0.5 on 2026-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_remove_skillmastery_skillmastery_plyr_form_idx_and_more'),
        ('challenges', '0003_challengerun_challenge_run_valid_command_budget_and_more'),
        ('players', '0002_remove_playerpreferences_theme_mode'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adventurelevelcompletion',
            constraint=models.CheckConstraint(condition=models.Q(('stars__lte', 3)), name='adventure_completion_stars_lte_3'),
        ),
        migrations.AddConstraint(
            model_name='challengetrialcompletion',
            constraint=models.CheckConstraint(condition=models.Q(('stars__lte', 3)), name='challenge_completion_stars_lte_3'),
        ),
    ]
