# Generated by Django 6.0.5 on 2026-07-19 17:11

from django.db import migrations, models


def normalize_progress_invariants(apps, schema_editor):
    database = schema_editor.connection.alias
    CoinTransaction = apps.get_model("progress", "CoinTransaction")
    StreakRecord = apps.get_model("progress", "StreakRecord")

    # Zero-value rows are neither credits nor debits and current services never
    # create them. Removing them gives the ledger one unambiguous meaning.
    CoinTransaction.objects.using(database).filter(amount=0).delete()
    StreakRecord.objects.using(database).filter(
        longest_streak__lt=models.F("current_streak")
    ).update(longest_streak=models.F("current_streak"))


class Migration(migrations.Migration):
    # Commit data repairs before PostgreSQL installs constraints. Keeping the
    # UPDATE and ALTER TABLE in one transaction leaves pending FK trigger events.
    atomic = False

    dependencies = [
        ("players", "0002_remove_playerpreferences_theme_mode"),
        ("progress", "0002_adventurelevelcompletion_adventure_completion_stars_lte_3_and_more"),
    ]

    operations = [
        migrations.RunPython(
            normalize_progress_invariants,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="cointransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="coin_transaction_amount_nonzero",
            ),
        ),
    ]
