# Generated by Django 6.0.5 on 2026-06-10 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_rename_adventureproblem_adventurequest_and_more'),
        ('challenges', '0002_rename_challengelevel_challengequest_and_more'),
        ('progress', '0002_wallet_cointransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='problemcompletion',
            name='unique_adventure_problem_completion',
        ),
        migrations.RemoveConstraint(
            model_name='problemcompletion',
            name='unique_challenge_level_completion',
        ),
        migrations.RenameField(
            model_name='problemcompletion',
            old_name='adventure_problem',
            new_name='adventure_quest',
        ),
        migrations.RenameField(
            model_name='problemcompletion',
            old_name='challenge_level',
            new_name='challenge_quest',
        ),
        migrations.AddConstraint(
            model_name='problemcompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('adventure_quest__isnull', False)), fields=('user', 'adventure_quest'), name='unique_adventure_quest_completion'),
        ),
        migrations.AddConstraint(
            model_name='problemcompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('challenge_quest__isnull', False)), fields=('user', 'challenge_quest'), name='unique_challenge_quest_completion'),
        ),
    ]
