# Generated by Django 5.2.11 on 2026-07-20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("progress", "0004_streakrecord_streak_longest_gte_current"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentProgress",
        ),
    ]
