# Generated by Django 6.0.5 on 2026-08-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpreferences',
            name='onboarding_phase',
            field=models.CharField(choices=[('stories', 'Stories'), ('shop', 'Shop'), ('purchase', 'Purchase'), ('home', 'Home'), ('equip', 'Equip'), ('done', 'Done')], default='done', max_length=16),
        ),
    ]
