# Generated by Django 6.0.7 on 2026-07-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerpreferences",
            name="theme_mode",
        ),
    ]
