# Generated by Django 6.0.7 on 2026-07-10 18:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_slug', models.CharField(max_length=32)),
                ('coins', models.PositiveIntegerField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('checkout_key', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True, max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitcoin_purchases', to='players.player')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['player', 'status'], name='gcpurchase_player_status_idx')],
            },
        ),
    ]
