# Generated by Django 6.0.5 on 2026-06-17 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
        ('assets', '0001_initial'),
        ('authoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_kind', models.CharField(choices=[('asset', 'Asset'), ('content_definition', 'Content definition'), ('archive_design', 'Archive design')], max_length=24)),
                ('price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.archivedesign')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('content_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authoring.contentdefinition')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_kind', models.CharField(choices=[('asset', 'Asset'), ('content_definition', 'Content definition'), ('archive_design', 'Archive design')], max_length=24)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('archive_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.archivedesign')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('content_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authoring.contentdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
                ('source_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.storelisting')),
            ],
            options={
                'ordering': ['-granted_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='storelisting',
            index=models.Index(fields=['item_kind', 'status'], name='store_listing_kind_status_idx'),
        ),
        migrations.AddIndex(
            model_name='storelisting',
            index=models.Index(fields=['seller', 'status'], name='store_listing_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['user', 'item_kind'], name='entitlement_user_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('asset__isnull', False)), fields=('user', 'asset'), name='unique_asset_entitlement_per_user'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('content_definition__isnull', False)), fields=('user', 'content_definition'), name='unique_content_entitlement_per_user'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('archive_design__isnull', False)), fields=('user', 'archive_design'), name='unique_tower_entitlement_per_user'),
        ),
    ]
