# Generated by Django 6.0.5 on 2026-06-13 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_asset_kind_towerpieceasset'),
        ('authoring', '0001_initial'),
        ('marketplace', '0001_initial'),
        ('towers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='tower_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='towers.towerdesign'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storelisting',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AddField(
            model_name='storelisting',
            name='content_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authoring.contentdefinition'),
        ),
        migrations.AddField(
            model_name='storelisting',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storelisting',
            name='tower_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='towers.towerdesign'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='source_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.storelisting'),
        ),
        migrations.AddIndex(
            model_name='storelisting',
            index=models.Index(fields=['item_kind', 'status'], name='store_listing_kind_status_idx'),
        ),
        migrations.AddIndex(
            model_name='storelisting',
            index=models.Index(fields=['seller', 'status'], name='store_listing_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['user', 'item_kind'], name='entitlement_user_kind_idx'),
        ),
    ]
