# Generated by Django 6.0.5 on 2026-06-13 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_kind_towerpieceasset'),
        ('authoring', '0001_initial'),
        ('marketplace', '0002_initial'),
        ('towers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('asset__isnull', False)), fields=('user', 'asset'), name='unique_asset_entitlement_per_user'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('content_definition__isnull', False)), fields=('user', 'content_definition'), name='unique_content_entitlement_per_user'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('tower_design__isnull', False)), fields=('user', 'tower_design'), name='unique_tower_entitlement_per_user'),
        ),
    ]
