# Generated by Django 6.0.5 on 2026-06-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('cards', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Storey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='CommandSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('base_command', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('mental_model', models.JSONField(blank=True, default=dict)),
                ('command_preview', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_topics', to='curriculum.storey')),
            ],
            options={
                'ordering': ['module__sort_order', 'sort_order', 'base_command'],
                'unique_together': {('module', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CommandForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('usage_form', models.CharField(max_length=140)),
                ('label', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('command_preview', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='curriculum.commandskill')),
            ],
            options={
                'ordering': ['topic__sort_order', 'sort_order', 'usage_form'],
                'unique_together': {('topic', 'slug')},
            },
        ),
    ]
