# Generated by Django 6.0.7 on 2026-07-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('base_command', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('mental_model', models.JSONField(blank=True, default=dict)),
                ('command_preview', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'base_command'],
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_key', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'library entries',
                'ordering': ['command_key'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('narrative_brief', models.JSONField(blank=True, default=dict)),
                ('price', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('world_slug', models.SlugField(default='arcane-spire', max_length=64)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=16)),
                ('prerequisite_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unlocks_stories', to='curriculum.story')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('narrative_brief', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('is_playable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('battle_stage', models.JSONField(blank=True, default=dict)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='curriculum.story')),
            ],
            options={
                'ordering': ['sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ChapterLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.chapter')),
                ('source_content_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_lessons', to='authoring.contentdefinition')),
            ],
            options={
                'ordering': ['chapter__sort_order', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_lesson_chapter_slug')],
            },
        ),
        migrations.CreateModel(
            name='CommandForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('usage_form', models.CharField(max_length=140)),
                ('label', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('command_preview', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('is_playable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_forms', to='curriculum.chapter')),
                ('command_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_forms', to='curriculum.commandskill')),
            ],
            options={
                'ordering': ['command_skill__sort_order', 'sort_order', 'usage_form'],
                'constraints': [models.UniqueConstraint(fields=('command_skill', 'slug'), name='unique_command_form_skill_slug')],
            },
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['story', 'sort_order'], name='chapter_story_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('story', 'number'), name='unique_chapter_story_number'),
        ),
    ]
