# Generated by Django 6.0.5 on 2026-06-17 06:39

import curriculum.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('chest_rewards', models.JSONField(blank=True, default=curriculum.models.default_chest_rewards)),
                ('mob_roster', models.JSONField(blank=True, default=list)),
                ('boss_roster', models.JSONField(blank=True, default=list)),
                ('battle_stage', models.JSONField(blank=True, default=dict)),
                ('relic_layout', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_key', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'library entries',
                'ordering': ['command_key'],
            },
        ),
        migrations.CreateModel(
            name='CommandSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('base_command', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('mental_model', models.JSONField(blank=True, default=dict)),
                ('command_preview', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_skills', to='curriculum.chapter')),
            ],
            options={
                'ordering': ['chapter__sort_order', 'sort_order', 'base_command'],
                'unique_together': {('chapter', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CommandForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('usage_form', models.CharField(max_length=140)),
                ('label', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('command_preview', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('command_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_forms', to='curriculum.commandskill')),
            ],
            options={
                'ordering': ['command_skill__sort_order', 'sort_order', 'usage_form'],
                'unique_together': {('command_skill', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Tome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('placement', models.CharField(choices=[('above_adventure', 'Above the adventure'), ('below_adventure', 'Below the adventure'), ('below_challenges', 'Below the challenges')], default='above_adventure', max_length=32)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomes', to='curriculum.chapter')),
                ('source_content_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_tomes', to='authoring.contentdefinition')),
            ],
            options={
                'ordering': ['chapter__sort_order', 'sort_order', 'id'],
                'unique_together': {('chapter', 'slug')},
            },
        ),
    ]
