# Generated by Django 6.0.5 on 2026-06-10 14:15

from django.db import migrations, models

import curriculum.models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storey',
            name='chest_rewards',
            field=models.JSONField(blank=True, default=curriculum.models.default_chest_rewards),
        ),
    ]
