# Generated by Django 6.0.5 on 2026-09-12 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_chapter_is_orientation_chapterorientationlesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='price',
        ),
    ]
