# Generated by Django 6.0.5 on 2026-06-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_rename_module_storey_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandform',
            options={'ordering': ['command_skill__sort_order', 'sort_order', 'usage_form']},
        ),
        migrations.AlterModelOptions(
            name='commandskill',
            options={'ordering': ['storey__sort_order', 'sort_order', 'base_command']},
        ),
        migrations.AlterField(
            model_name='commandform',
            name='command_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_forms', to='curriculum.commandskill'),
        ),
        migrations.AlterField(
            model_name='commandskill',
            name='storey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_skills', to='curriculum.storey'),
        ),
    ]
