# Generated by Django 6.0.5 on 2026-06-11 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_commandform_options_alter_commandskill_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_key', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'library entries',
                'ordering': ['command_key'],
            },
        ),
        migrations.CreateModel(
            name='Tome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('placement', models.CharField(choices=[('above_adventure', 'Above the adventure'), ('below_adventure', 'Below the adventure'), ('below_challenges', 'Below the challenges')], default='above_adventure', max_length=32)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('storey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomes', to='curriculum.storey')),
            ],
            options={
                'ordering': ['storey__sort_order', 'sort_order', 'id'],
                'unique_together': {('storey', 'slug')},
            },
        ),
        migrations.DeleteModel(
            name='ConceptPage',
        ),
    ]
