# Generated by Django 6.0.5 on 2026-06-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_libraryentry_tome_delete_conceptpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storey',
            name='boss_roster',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storey',
            name='mob_roster',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
