# Generated by Django 6.0.5 on 2026-06-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0001_initial'),
        ('curriculum', '0006_storey_boss_roster_storey_mob_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='tome',
            name='source_content_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_tomes', to='authoring.contentdefinition'),
        ),
    ]
