# Generated by Django 6.0.5 on 2026-06-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_tome_source_content_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='storey',
            name='battle_stage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
