# Generated by Django 6.0.5 on 2026-09-19 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0008_adventureleveltierrun_changed_variant'),
        ('players', '0003_alter_playerpreferences_onboarding_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('clears', models.PositiveIntegerField(default=0)),
                ('best_accuracy', models.PositiveSmallIntegerField(default=0)),
                ('last_accuracy', models.PositiveSmallIntegerField(default=0)),
                ('shaky_form_keys', models.JSONField(blank=True, default=list)),
                ('first_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('adventure_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_progress', to='adventures.adventurelevel')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_progress', to='players.player')),
            ],
            options={
                'verbose_name_plural': 'drill progress',
                'indexes': [models.Index(fields=['player', 'adventure_level'], name='drill_plyr_level_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'adventure_level'), name='unique_drill_progress_player_level'), models.CheckConstraint(condition=models.Q(('best_accuracy__lte', 100), ('last_accuracy__lte', 100)), name='drill_progress_accuracy_is_percent'), models.CheckConstraint(condition=models.Q(('clears__lte', models.F('sessions'))), name='drill_progress_clears_lte_sessions')],
            },
        ),
    ]
