# Generated by Django 6.0.5 on 2026-09-19 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0008_adventureleveltierrun_changed_variant'),
        ('curriculum', '0003_remove_story_price'),
        ('drills', '0001_initial'),
        ('players', '0003_alter_playerpreferences_onboarding_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_label', models.CharField(blank=True, max_length=180)),
                ('sequence_task', models.TextField(blank=True)),
                ('sequence_steps', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drill', to='adventures.adventurelevel')),
            ],
            options={
                'ordering': ['adventure_level_id'],
            },
        ),
        migrations.CreateModel(
            name='DrillRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=16)),
                ('queue_state', models.JSONField(blank=True, default=dict)),
                ('answered', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('adventure_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_runs', to='adventures.adventurelevel')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_runs', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'adventure_level', 'status'], name='drill_run_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'started')), fields=('player', 'adventure_level'), name='unique_active_drill_run'), models.CheckConstraint(condition=models.Q(('correct__lte', models.F('answered'))), name='drill_run_correct_lte_answered')],
            },
        ),
        migrations.CreateModel(
            name='LevelDrillCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('form_key', models.CharField(max_length=160)),
                ('command', models.CharField(max_length=200)),
                ('intent', models.CharField(max_length=200)),
                ('base_command', models.CharField(max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('tokens', models.JSONField(default=list)),
                ('command_choices', models.JSONField(blank=True, default=list)),
                ('intent_choices', models.JSONField(blank=True, default=list)),
                ('blank', models.JSONField(blank=True, default=dict)),
                ('bank', models.JSONField(default=list)),
                ('command_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drill_cards', to='curriculum.commandform')),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='drills.leveldrill')),
            ],
            options={
                'ordering': ['drill_id', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['drill', 'sort_order'], name='drill_card_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('drill', 'form_key'), name='unique_drill_card_form_key')],
            },
        ),
    ]
