#!/usr/bin/env python3
"""Validate deployment-critical invariants in the $0 Render Blueprint."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
BLUEPRINT = ROOT / "render.yaml"


def fail(message: str) -> None:
    raise SystemExit(f"Render Blueprint check failed: {message}")


def by_name(items: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {str(item.get("name")): item for item in items}


def env_by_key(service: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {
        str(item["key"]): item
        for item in service.get("envVars", [])
        if isinstance(item, dict) and "key" in item
    }


def require_reference(variable: dict[str, Any], source: str, name: str, property_name: str) -> None:
    reference = variable.get(source)
    if not isinstance(reference, dict):
        fail(f"{variable.get('key')} must use {source}")
    if reference.get("name") != name or reference.get("property") != property_name:
        fail(f"{variable.get('key')} points at the wrong Render resource")


def require_self_env_reference(variable: dict[str, Any], env_var_key: str) -> None:
    reference = variable.get("fromService")
    expected = {
        "type": "web",
        "name": "git-it-app",
        "envVarKey": env_var_key,
    }
    if reference != expected:
        fail(f"{variable.get('key')} must reference git-it-app {env_var_key}")


def require_value(env: dict[str, dict[str, Any]], key: str, value: str) -> None:
    if env.get(key, {}).get("value") != value:
        fail(f"{key} must be {value}")


def require_secret_prompt(env: dict[str, dict[str, Any]], key: str) -> None:
    variable = env.get(key, {})
    if variable.get("sync") is not False or len(variable) != 2:
        fail(f"{key} must be supplied through a Render secret prompt")


def main() -> int:
    payload = yaml.safe_load(BLUEPRINT.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        fail("render.yaml must contain an object")

    services = by_name(payload.get("services", []))
    databases = payload.get("databases", [])
    expected_services = {"git-it-app", "git-it-cache"}
    if set(services) != expected_services:
        fail(f"expected services {sorted(expected_services)}, found {sorted(services)}")
    if databases:
        fail("Render Postgres must not be created; this preview uses existing Supabase")

    app = services["git-it-app"]
    cache = services["git-it-cache"]

    for service in services.values():
        if service.get("plan") != "free":
            fail(f"{service.get('name')} must remain on Render's Free plan")
        for paid_only_field in (
            "preDeployCommand",
            "initialDeployHook",
            "maxShutdownDelaySeconds",
            "disk",
        ):
            if paid_only_field in service:
                fail(f"{service.get('name')} cannot declare paid-only {paid_only_field}")
        if service.get("region") != "singapore":
            fail(f"{service.get('name')} must remain in Singapore")

    if (app.get("type"), app.get("runtime")) != ("web", "docker"):
        fail("git-it-app must remain a public Docker web service")
    if app.get("healthCheckPath") != "/api/health/live/":
        fail("app health check must use /api/health/live/")
    if cache.get("type") != "keyvalue" or cache.get("ipAllowList") != []:
        fail("Free Key Value must remain internal-only")
    if cache.get("persistenceMode") not in (None, "off"):
        fail("Free Key Value cannot enable persistence")

    dockerfile = ROOT / str(app.get("dockerfilePath", ""))
    context = ROOT / str(app.get("dockerContext", ""))
    if not dockerfile.is_file() or not context.is_dir():
        fail("combined app Docker paths do not exist")

    app_env = env_by_key(app)
    require_secret_prompt(app_env, "DATABASE_URL")
    require_reference(app_env["REDIS_URL"], "fromService", "git-it-cache", "connectionString")
    if "DEPLOYMENT_VERSION" in app_env:
        fail("DEPLOYMENT_VERSION must use Render's runtime RENDER_GIT_COMMIT fallback")
    for key, render_key in (
        ("DJANGO_ALLOWED_HOSTS", "RENDER_EXTERNAL_HOSTNAME"),
        ("DJANGO_CORS_ALLOWED_ORIGINS", "RENDER_EXTERNAL_URL"),
        ("DJANGO_CSRF_TRUSTED_ORIGINS", "RENDER_EXTERNAL_URL"),
        ("FRONTEND_BASE_URL", "RENDER_EXTERNAL_URL"),
    ):
        require_self_env_reference(app_env[key], render_key)

    if app_env.get("DJANGO_SECRET_KEY", {}).get("generateValue") is not True:
        fail("DJANGO_SECRET_KEY must be generated by Render")
    for key in (
        "DJANGO_SUPERUSER_USERNAME",
        "DJANGO_SUPERUSER_EMAIL",
        "DJANGO_SUPERUSER_PASSWORD",
        "MAILGUN_API_KEY",
        "MAILGUN_DOMAIN",
        "DEFAULT_FROM_EMAIL",
    ):
        require_secret_prompt(app_env, key)

    require_value(app_env, "DJANGO_DEBUG", "False")
    require_value(app_env, "DJANGO_MIGRATE_ON_STARTUP", "True")
    require_value(app_env, "DJANGO_SEED_ON_STARTUP", "True")
    require_value(app_env, "DATABASE_SSLMODE", "require")
    require_value(app_env, "GUNICORN_WORKERS", "1")
    require_value(app_env, "JWT_COOKIE_SECURE", "True")
    require_value(app_env, "JWT_COOKIE_SAMESITE", "Strict")
    require_value(app_env, "ALLOW_DESTRUCTIVE_SEED_RESET", "False")
    require_value(app_env, "EMAIL_BACKEND", "common.email_backends.MailgunEmailBackend")
    require_value(app_env, "MAILGUN_API_BASE_URL", "https://api.mailgun.net")
    require_value(app_env, "MAILGUN_TIMEOUT_SECONDS", "10")

    proxy_ranges = str(app_env.get("DJANGO_TRUSTED_PROXY_IPS", {}).get("value", ""))
    if "0.0.0.0/0" in proxy_ranges or "::/0" in proxy_ranges:
        fail("the public app must not trust forwarding headers from every IP")

    print("Render Blueprint check passed ($0 app + cache, external Supabase + Mailgun HTTPS).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
