# Generated by Django 6.0.7 on 2026-07-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0002_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.TextField()),
                ('terminal_output', models.TextField(blank=True)),
                ('result_category', models.CharField(choices=[('TargetMatched', 'Target matched'), ('TargetNotYetMatched', 'Target not yet matched'), ('Unprocessable', 'Unprocessable'), ('Invalid', 'Invalid')], max_length=32)),
                ('command_classification', models.CharField(choices=[('counted_action', 'Counted action'), ('non_counted_diagnostic', 'Non-counted diagnostic'), ('unprocessable', 'Unprocessable')], max_length=32)),
                ('normalized_command', models.TextField(blank=True)),
                ('was_processable', models.BooleanField(default=False)),
                ('counted_increment', models.PositiveIntegerField(default=0)),
                ('attempt_number', models.PositiveIntegerField()),
                ('counted_total_after', models.PositiveIntegerField(default=0)),
                ('state_hash', models.CharField(blank=True, max_length=128)),
                ('expected_state_hash', models.CharField(blank=True, max_length=128)),
                ('repository_state', models.JSONField(blank=True, default=dict)),
                ('visualization_snapshot', models.JSONField(blank=True, default=dict)),
                ('contextual_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='adventures.adventurerun')),
                ('challenge_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='challenges.challengerun')),
            ],
            options={
                'indexes': [models.Index(fields=['challenge_run', 'id'], name='cmdstep_run_id_idx'), models.Index(fields=['attempt', 'id'], name='cmdstep_attempt_id_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('attempt__isnull', True), ('challenge_run__isnull', False)), models.Q(('attempt__isnull', False), ('challenge_run__isnull', True)), _connector='OR'), name='command_step_exactly_one_parent')],
            },
        ),
    ]
