# Generated by Django 6.0.5 on 2026-06-17 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0002_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.TextField()),
                ('terminal_output', models.TextField(blank=True)),
                ('result_category', models.CharField(choices=[('TargetMatched', 'Target matched'), ('TargetNotYetMatched', 'Target not yet matched'), ('Unprocessable', 'Unprocessable'), ('Invalid', 'Invalid')], max_length=32)),
                ('command_classification', models.CharField(choices=[('counted_action', 'Counted action'), ('non_counted_diagnostic', 'Non-counted diagnostic'), ('unprocessable', 'Unprocessable')], max_length=32)),
                ('counted_increment', models.PositiveIntegerField(default=0)),
                ('attempt_number', models.PositiveIntegerField()),
                ('counted_total_after', models.PositiveIntegerField(default=0)),
                ('state_hash', models.CharField(blank=True, max_length=128)),
                ('expected_state_hash', models.CharField(blank=True, max_length=128)),
                ('repository_state', models.JSONField(blank=True, default=dict)),
                ('visualization_snapshot', models.JSONField(blank=True, default=dict)),
                ('contextual_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='adventures.adventurelevelattempt')),
                ('challenge_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='challenges.challengerun')),
            ],
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_command', models.TextField()),
                ('normalized_command', models.TextField()),
                ('was_processable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='command_log', to='practice.commandstep')),
            ],
        ),
        migrations.AddIndex(
            model_name='commandstep',
            index=models.Index(fields=['challenge_run', 'id'], name='cmdstep_run_id_idx'),
        ),
        migrations.AddIndex(
            model_name='commandstep',
            index=models.Index(fields=['attempt', 'id'], name='cmdstep_attempt_id_idx'),
        ),
    ]
