# Generated by Django 6.0.5 on 2026-07-19 17:11

from django.db import migrations, models


def normalize_command_step_counts(apps, schema_editor):
    CommandStep = apps.get_model("practice", "CommandStep")
    steps = CommandStep.objects.using(schema_editor.connection.alias)
    steps.filter(attempt_number__lt=1).update(attempt_number=1)
    steps.filter(counted_increment__gt=1).update(counted_increment=1)
    steps.filter(counted_total_after__lt=models.F("counted_increment")).update(
        counted_total_after=models.F("counted_increment")
    )


class Migration(migrations.Migration):
    # Commit data repairs before PostgreSQL installs constraints. Keeping the
    # UPDATE and ALTER TABLE in one transaction leaves pending FK trigger events.
    atomic = False

    dependencies = [
        ("adventures", "0004_remove_skillmastery_skillmastery_plyr_form_idx_and_more"),
        ("challenges", "0003_challengerun_challenge_run_valid_command_budget_and_more"),
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            normalize_command_step_counts,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="commandstep",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attempt_number__gte", 1),
                    ("counted_increment__lte", 1),
                    ("counted_total_after__gte", models.F("counted_increment")),
                ),
                name="command_step_valid_counts",
            ),
        ),
    ]
