# Generated by Django 6.0.5 on 2026-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_rename_adventureproblem_adventurequest_and_more'),
        ('challenges', '0002_rename_challengelevel_challengequest_and_more'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commandstep',
            index=models.Index(fields=['attempt', 'id'], name='cmdstep_attempt_id_idx'),
        ),
    ]
