# Generated by Django 6.0.5 on 2026-06-11 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_challenge_options_alter_challengequest_options_and_more'),
        ('practice', '0003_rename_session_challenge_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandstep',
            name='challenge_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='challenges.challengerun'),
        ),
    ]
