# Generated by Django 6.0.5 on 2026-09-22 05:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_alter_playerpreferences_onboarding_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCommandIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_key', models.CharField(max_length=160)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'teaching_key'), name='unique_player_command_introduction')],
            },
        ),
    ]
