# Generated by Django 6.0.5 on 2026-09-22 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0008_adventureleveltierrun_changed_variant'),
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCommandIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_key', models.CharField(max_length=160)),
                ('revision', models.PositiveIntegerField()),
                ('context_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adventures.adventureleveltierrun')),
            ],
        ),
    ]
