# Generated by Django 6.0.5 on 2026-05-18 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=12)),
                ('narrative', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandCountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_counted_commands', models.PositiveIntegerField()),
                ('max_counted_commands', models.PositiveIntegerField()),
                ('non_counted_patterns', models.JSONField(blank=True, default=list)),
                ('difficulty_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='command_policy', to='scenarios.difficultyinstance')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioSkillFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('focus', models.CharField(max_length=140)),
                ('narrative', models.TextField()),
                ('task_prompt', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='learning.learningunit')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='learning.lesson')),
            ],
            options={
                'ordering': ['learning_unit__sort_order', 'lesson__sort_order', 'sort_order'],
                'unique_together': {('learning_unit', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='difficultyinstance',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_instances', to='scenarios.scenarioskillfocus'),
        ),
        migrations.CreateModel(
            name='ScenarioVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=80)),
                ('structure_signature', models.CharField(max_length=120)),
                ('initial_state', models.JSONField()),
                ('target_state', models.JSONField()),
                ('expected_state_diagram', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='scenarios.scenarioskillfocus')),
            ],
            options={
                'unique_together': {('scenario', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_entry_point', models.CharField(max_length=40)),
                ('mode', models.CharField(choices=[('primary', 'Primary'), ('review', 'Review')], default='primary', max_length=16)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='started', max_length=16)),
                ('ocg_satisfied_at_start', models.BooleanField(default=False)),
                ('rta_eligible', models.BooleanField(default=False)),
                ('rta_success', models.BooleanField(default=False)),
                ('changed_variant', models.BooleanField(default=False)),
                ('command_policy_snapshot', models.JSONField(default=dict)),
                ('repository_state', models.JSONField(default=dict)),
                ('counted_action_total', models.PositiveIntegerField(default=0)),
                ('non_counted_diagnostic_total', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('retry_index', models.PositiveIntegerField(default=0)),
                ('first_attempt_star_eligible', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=160)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('difficulty_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scenarios.difficultyinstance')),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.learningunit')),
                ('prior_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_sessions', to='scenarios.scenariosession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scenarios.scenarioskillfocus')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scenarios.scenariovariant')),
            ],
        ),
        migrations.CreateModel(
            name='StepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.TextField()),
                ('terminal_output', models.TextField(blank=True)),
                ('result_category', models.CharField(choices=[('TargetMatched', 'Target matched'), ('TargetNotYetMatched', 'Target not yet matched'), ('Unprocessable', 'Unprocessable'), ('Invalid', 'Invalid')], max_length=32)),
                ('command_classification', models.CharField(choices=[('counted_action', 'Counted action'), ('non_counted_diagnostic', 'Non-counted diagnostic'), ('unprocessable', 'Unprocessable')], max_length=32)),
                ('counted_increment', models.PositiveIntegerField(default=0)),
                ('attempt_number', models.PositiveIntegerField()),
                ('counted_total_after', models.PositiveIntegerField(default=0)),
                ('state_hash', models.CharField(blank=True, max_length=128)),
                ('expected_state_hash', models.CharField(blank=True, max_length=128)),
                ('repository_state', models.JSONField(blank=True, default=dict)),
                ('contextual_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='scenarios.scenariosession')),
            ],
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_command', models.TextField()),
                ('normalized_command', models.TextField()),
                ('was_processable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='command_log', to='scenarios.steplog')),
            ],
        ),
        migrations.CreateModel(
            name='TargetStateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.JSONField()),
                ('target_state_hash', models.CharField(blank=True, max_length=128)),
                ('difficulty_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target_rule', to='scenarios.difficultyinstance')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='difficultyinstance',
            unique_together={('scenario', 'difficulty')},
        ),
        migrations.CreateModel(
            name='CompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_attempt_star', models.BooleanField(default=False)),
                ('counted_action_total', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('difficulty_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.difficultyinstance')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenariosession')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenarioskillfocus')),
            ],
            options={
                'unique_together': {('user', 'difficulty_instance')},
            },
        ),
    ]
