# Generated by Django 6.0.5 on 2026-06-06 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('base_command', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('mental_model', models.JSONField(blank=True, default=dict)),
                ('command_preview', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_topics', to='learning.learningmodule')),
            ],
            options={
                'ordering': ['module__sort_order', 'sort_order', 'base_command'],
                'unique_together': {('module', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CommandUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('usage_form', models.CharField(max_length=140)),
                ('label', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('command_preview', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='scenarios.commandtopic')),
            ],
            options={
                'ordering': ['topic__sort_order', 'sort_order', 'usage_form'],
                'unique_together': {('topic', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CommandDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('required_successful_attempts', models.PositiveIntegerField(default=3)),
                ('min_counted_commands', models.PositiveIntegerField(default=1)),
                ('max_counted_commands', models.PositiveIntegerField(default=4)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('student_context', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='scenarios.commandusage')),
            ],
            options={
                'ordering': ['usage__topic__sort_order', 'usage__sort_order', 'sort_order'],
                'unique_together': {('usage', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProblemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=80)),
                ('structure_signature', models.CharField(blank=True, max_length=120)),
                ('initial_state', models.JSONField(default=dict)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('target_state', models.JSONField(blank=True, default=dict)),
                ('expected_state_diagram', models.JSONField(blank=True, default=dict)),
                ('solution_commands', models.JSONField(blank=True, default=list)),
                ('case_id', models.CharField(blank=True, max_length=160)),
                ('semantic_key', models.CharField(blank=True, max_length=240)),
                ('parameter_context', models.JSONField(blank=True, default=dict)),
                ('student_context', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('command_drill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='scenarios.commanddrill')),
            ],
            options={
                'ordering': ['command_drill_id', 'workflow_level_id', 'semantic_key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_kind', models.CharField(choices=[('command_drill', 'Command drill'), ('workflow_scenario', 'Workflow scenario')], max_length=24)),
                ('source_entry_point', models.CharField(max_length=40)),
                ('mode', models.CharField(choices=[('primary', 'Primary'), ('review', 'Review')], default='primary', max_length=16)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='started', max_length=16)),
                ('difficulty', models.CharField(blank=True, max_length=12)),
                ('rta_eligible', models.BooleanField(default=False)),
                ('rta_success', models.BooleanField(default=False)),
                ('changed_variant', models.BooleanField(default=False)),
                ('looped_variant', models.BooleanField(default=False)),
                ('command_budget_snapshot', models.JSONField(default=dict)),
                ('repository_state', models.JSONField(default=dict)),
                ('counted_action_total', models.PositiveIntegerField(default=0)),
                ('non_counted_diagnostic_total', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('retry_index', models.PositiveIntegerField(default=0)),
                ('first_attempt_star_eligible', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=160)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('command_drill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scenarios.commanddrill')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.learningmodule')),
                ('prior_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_sessions', to='scenarios.practicesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scenarios.problemvariant')),
            ],
        ),
        migrations.CreateModel(
            name='StepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.TextField()),
                ('terminal_output', models.TextField(blank=True)),
                ('result_category', models.CharField(choices=[('TargetMatched', 'Target matched'), ('TargetNotYetMatched', 'Target not yet matched'), ('Unprocessable', 'Unprocessable'), ('Invalid', 'Invalid')], max_length=32)),
                ('command_classification', models.CharField(choices=[('counted_action', 'Counted action'), ('non_counted_diagnostic', 'Non-counted diagnostic'), ('unprocessable', 'Unprocessable')], max_length=32)),
                ('counted_increment', models.PositiveIntegerField(default=0)),
                ('attempt_number', models.PositiveIntegerField()),
                ('counted_total_after', models.PositiveIntegerField(default=0)),
                ('state_hash', models.CharField(blank=True, max_length=128)),
                ('expected_state_hash', models.CharField(blank=True, max_length=128)),
                ('repository_state', models.JSONField(blank=True, default=dict)),
                ('visualization_snapshot', models.JSONField(blank=True, default=dict)),
                ('contextual_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='scenarios.practicesession')),
            ],
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_command', models.TextField()),
                ('normalized_command', models.TextField()),
                ('was_processable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='command_log', to='scenarios.steplog')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('narrative', models.TextField(blank=True)),
                ('command_topics', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_scenarios', to='learning.learningmodule')),
            ],
            options={
                'ordering': ['module__sort_order', 'sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='practicesession',
            name='workflow_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scenarios.workflowscenario'),
        ),
        migrations.CreateModel(
            name='WorkflowScenarioLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=12)),
                ('narrative', models.TextField(blank=True)),
                ('task_prompt', models.TextField(blank=True)),
                ('required_successful_attempts', models.PositiveIntegerField(default=2)),
                ('min_counted_commands', models.PositiveIntegerField(default=1)),
                ('max_counted_commands', models.PositiveIntegerField(default=8)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('student_context', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='scenarios.workflowscenario')),
            ],
            options={
                'ordering': ['scenario__sort_order', 'difficulty'],
            },
        ),
        migrations.AddField(
            model_name='problemvariant',
            name='workflow_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='scenarios.workflowscenariolevel'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='workflow_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scenarios.workflowscenariolevel'),
        ),
        migrations.CreateModel(
            name='CompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_kind', models.CharField(choices=[('command_drill', 'Command drill'), ('workflow_scenario', 'Workflow scenario')], max_length=24)),
                ('first_attempt_star', models.BooleanField(default=False)),
                ('counted_action_total', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('command_drill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.commanddrill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scenarios.practicesession')),
                ('workflow_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.workflowscenariolevel')),
            ],
        ),
        migrations.AddIndex(
            model_name='steplog',
            index=models.Index(fields=['session', 'id'], name='steplog_session_id_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowscenario',
            unique_together={('module', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowscenariolevel',
            unique_together={('scenario', 'difficulty')},
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'mode', 'status'], name='practice_user_mode_status_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'practice_kind', 'status'], name='practice_user_kind_status_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'workflow_level', '-id'], name='practice_user_level_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'command_drill', '-id'], name='practice_user_drill_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='completionrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('command_drill__isnull', False)), fields=('user', 'command_drill'), name='unique_command_drill_completion'),
        ),
        migrations.AddConstraint(
            model_name='completionrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('workflow_level__isnull', False)), fields=('user', 'workflow_level'), name='unique_workflow_level_completion'),
        ),
    ]
