# Generated by Django 6.0.5 on 2026-05-19 16:43

from django.db import migrations, models


def clear_legacy_skill_focus_prompts(apps, schema_editor):
    ScenarioSkillFocus = apps.get_model("scenarios", "ScenarioSkillFocus")
    for scenario in ScenarioSkillFocus.objects.filter(difficulty_instances__isnull=False).distinct():
        scenario.narrative = ""
        scenario.task_prompt = ""
        scenario.save(update_fields=["narrative", "task_prompt"])


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_rename_orientation_completion_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioskillfocus',
            name='demo_dag_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scenarioskillfocus',
            name='demo_explanation_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scenarioskillfocus',
            name='demo_repository_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scenarioskillfocus',
            name='primary_focus_commands',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scenarioskillfocus',
            name='related_git_concepts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scenarioskillfocus',
            name='safe_demo_commands',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scenarioskillfocus',
            name='short_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scenarioskillfocus',
            name='skill_focus_type',
            field=models.CharField(choices=[('command_specific', 'Command-specific'), ('concept_specific', 'Concept-specific'), ('workflow_specific', 'Workflow-specific')], default='command_specific', max_length=24),
        ),
        migrations.AddField(
            model_name='scenarioskillfocus',
            name='summary',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='scenarioskillfocus',
            name='supporting_inspection_commands',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='scenarioskillfocus',
            name='narrative',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scenarioskillfocus',
            name='task_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(clear_legacy_skill_focus_prompts, migrations.RunPython.noop),
    ]
