# Generated by Django 6.0.5 on 2026-05-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_scenarioskillfocus_demo_dag_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficultyinstance',
            name='completion_type',
            field=models.CharField(choices=[('state_based', 'State based'), ('inspection', 'Inspection'), ('expanded_state_based', 'Expanded state based')], default='state_based', max_length=32),
        ),
        migrations.AddField(
            model_name='scenariovariant',
            name='expected_observations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scenariovariant',
            name='solution_commands',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scenariovariant',
            name='target_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
