# Generated by Django 6.0.5 on 2026-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0006_latency_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficultyinstance',
            name='required_successful_attempts',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
