# Generated by Codex on 2026-05-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0007_difficultyinstance_required_successful_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioGenerationBlueprint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField()),
                ("slug_template", models.CharField(max_length=160)),
                ("label_template", models.CharField(max_length=160)),
                ("blueprint_signature", models.CharField(max_length=160)),
                ("subtemplate_signature", models.CharField(blank=True, max_length=160)),
                ("parameter_pools", models.JSONField(blank=True, default=dict)),
                ("initial_state_template", models.JSONField(blank=True, default=dict)),
                ("target_rule_template", models.JSONField(blank=True, default=dict)),
                ("solution_commands_template", models.JSONField(blank=True, default=list)),
                ("expected_observations_template", models.JSONField(blank=True, default=dict)),
                ("student_context_template", models.JSONField(blank=True, default=dict)),
                ("generation_count", models.PositiveIntegerField(default=1)),
                ("max_combinations", models.PositiveIntegerField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "difficulty_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_blueprints",
                        to="scenarios.difficultyinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["difficulty_instance_id", "sort_order", "id"],
                "unique_together": {("difficulty_instance", "slug")},
            },
        ),
        migrations.AddField(
            model_name="scenariovariant",
            name="blueprint_signature",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="scenariovariant",
            name="generation_seed",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="scenariovariant",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scenariovariant",
            name="parameter_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scenariovariant",
            name="student_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scenariovariant",
            name="subtemplate_signature",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="scenariovariant",
            name="variant_fingerprint",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="scenariovariant",
            name="generated_from_blueprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_variants",
                to="scenarios.scenariogenerationblueprint",
            ),
        ),
    ]
