# Generated by Django 6.0.5 on 2026-05-25 06:07

from django.db import migrations, models
from django.utils.text import slugify


def populate_authored_case_identity(apps, schema_editor):
    ScenarioVariant = apps.get_model("scenarios", "ScenarioVariant")
    seen = set()
    for variant in (
        ScenarioVariant.objects.select_related("difficulty_instance")
        .order_by("difficulty_instance_id", "id")
    ):
        context = variant.parameter_context or {}
        case_id = str(context.get("case_id") or "").strip() or f"legacy-{variant.id}"
        template_key = (
            variant.blueprint_signature
            or variant.structure_signature
            or variant.slug
            or "legacy"
        )
        difficulty = getattr(variant.difficulty_instance, "difficulty", "") or "unknown"
        template_slug = slugify(str(template_key)) or "legacy"
        semantic_key = f"{difficulty}:{template_slug}:{case_id}"
        if len(semantic_key) > 240:
            semantic_key = f"{semantic_key[:199]}:{variant.id}"

        uniqueness_key = (variant.difficulty_instance_id, semantic_key)
        if uniqueness_key in seen:
            semantic_key = f"legacy:{variant.id}:{semantic_key[:220]}"
            uniqueness_key = (variant.difficulty_instance_id, semantic_key)
        seen.add(uniqueness_key)

        variant.case_id = case_id[:160]
        variant.semantic_key = semantic_key[:240]
        variant.save(update_fields=["case_id", "semantic_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0013_deprecate_inspection_scenarios'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scenariogenerationblueprint',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scenariogenerationblueprint',
            name='difficulty_instance',
        ),
        migrations.AlterUniqueTogether(
            name='scenariovariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scenariovariant',
            name='case_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='scenariovariant',
            name='semantic_key',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.RunPython(
            populate_authored_case_identity,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='scenariovariant',
            constraint=models.UniqueConstraint(fields=('difficulty_instance', 'slug'), name='unique_variant_slug_per_difficulty'),
        ),
        migrations.AddConstraint(
            model_name='scenariovariant',
            constraint=models.UniqueConstraint(fields=('difficulty_instance', 'semantic_key'), name='unique_variant_semantic_key_per_difficulty'),
        ),
        migrations.RemoveField(
            model_name='scenariovariant',
            name='blueprint_signature',
        ),
        migrations.RemoveField(
            model_name='scenariovariant',
            name='generated_from_blueprint',
        ),
        migrations.RemoveField(
            model_name='scenariovariant',
            name='generation_seed',
        ),
        migrations.RemoveField(
            model_name='scenariovariant',
            name='is_generated',
        ),
        migrations.RemoveField(
            model_name='scenariovariant',
            name='subtemplate_signature',
        ),
        migrations.RemoveField(
            model_name='scenariovariant',
            name='variant_fingerprint',
        ),
        migrations.DeleteModel(
            name='ScenarioGenerationBlueprint',
        ),
    ]
