# Generated by Codex on 2026-05-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0014_static_authored_variants"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TargetStateRule",
        ),
    ]
