# Generated by Django 6.0.5 on 2026-06-17 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('store', 'Store')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('origin', models.CharField(choices=[('personal', 'Personal'), ('official_fork', 'Official fork')], default='personal', max_length=16)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_designs', to=settings.AUTH_USER_MODEL)),
                ('source_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixes', to='archive.archivedesign')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RelicPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_index', models.PositiveIntegerField(default=0)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('scale', models.FloatField(default=1)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('rotation', models.FloatField(default=0)),
                ('z_index', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('normal', 'Normal'), ('adventure', 'Adventure'), ('challenge', 'Challenge'), ('tome', 'Tome')], default='normal', max_length=16)),
                ('interactive_viewbox', models.JSONField(blank=True, default=dict)),
                ('landing_viewbox', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('archive_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relics', to='archive.archivedesign')),
            ],
            options={
                'ordering': ['archive_design_id', 'chapter_index', 'z_index', 'id'],
            },
        ),
    ]
