# Generated by Django 6.0.5 on 2026-06-17 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
        ('assets', '0001_initial'),
        ('authoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relicplacement',
            name='content_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relic_placements', to='authoring.contentdefinition'),
        ),
        migrations.AddField(
            model_name='relicplacement',
            name='relic_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset'),
        ),
        migrations.AddIndex(
            model_name='archivedesign',
            index=models.Index(fields=['owner', 'status'], name='archive_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedesign',
            index=models.Index(fields=['visibility', 'status'], name='archive_vis_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='archivedesign',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_archive_design_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='archivedesign',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner',), name='unique_active_archive_design_per_owner'),
        ),
        migrations.AddIndex(
            model_name='relicplacement',
            index=models.Index(fields=['archive_design', 'chapter_index'], name='relic_design_chapter_idx'),
        ),
    ]
