#!/usr/bin/env python3
"""Fail CI when generated curriculum target states drift from authored variants.

``generated_targets.py`` is intentionally committed because the runtime seed path
needs stable, precomputed repository targets. This guard keeps that generated
artifact honest without running the full TypeScript replay engine on every CI
job:

* every authored variant ``case_id`` must have exactly one generated target;
* no generated target may exist without an authored variant;
* every generated target must keep the repository-state containers that the
  backend evaluator expects.

When a variant solution changes, run:

    cd backend && python manage.py generate_targets
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[2]
BACKEND = ROOT / "backend"
TARGETS_FILE = BACKEND / "curriculum" / "seed_data" / "generated" / "generated_targets.py"
OLD_TARGETS_FILE = BACKEND / "curriculum" / "seed_data" / "generated_targets.py"
EXPECTED_HEADER_PREFIX = "# Generated by `python manage.py generate_targets`. Do not edit by hand."

REPOSITORY_DICT_KEYS = {
    "branches",
    "head",
    "staging",
    "working_tree",
    "conflict_details",
    "remotes",
    "remote_branches",
    "upstream_tracking",
    "tags",
    "remote_tags",
    "partial_hunks",
    "replaced_commits",
    "operation_metadata",
    "remote_fixtures",
    "remote_updates",
}
REPOSITORY_LIST_KEYS = {"commits", "conflicts", "stash_stack", "reflog"}


def _load_seed_modules() -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    sys.path.insert(0, str(BACKEND))
    from curriculum.seed_data.adventure_levels import ADVENTURE_LEVELS  # noqa: PLC0415
    from curriculum.seed_data.challenges import CHALLENGES  # noqa: PLC0415
    from curriculum.seed_data.generated.generated_targets import TARGET_STATES  # noqa: PLC0415

    return ADVENTURE_LEVELS, CHALLENGES, TARGET_STATES


def _collect_case_ids(adventure_levels: list[dict[str, Any]], challenges: list[dict[str, Any]]) -> set[str]:
    case_ids: set[str] = set()
    duplicates: set[str] = set()

    def add(case_id: Any) -> None:
        if not case_id:
            return
        if not isinstance(case_id, str):
            raise ValueError(f"variant case_id must be a string, got {case_id!r}")
        if case_id in case_ids:
            duplicates.add(case_id)
        case_ids.add(case_id)

    for level in adventure_levels:
        for variant in level.get("variants", []):
            add(variant.get("case_id"))

    for challenge in challenges:
        for level in challenge.get("levels", []):
            for variant in level.get("variants", []):
                add(variant.get("case_id"))

    if duplicates:
        raise ValueError(f"duplicate variant case_id(s): {', '.join(sorted(duplicates))}")
    return case_ids


def _validate_target_shape(case_id: str, target: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(target, dict):
        return [f"{case_id}: target state must be an object"]

    for key in REPOSITORY_DICT_KEYS:
        if key in target and not isinstance(target.get(key), dict):
            errors.append(f"{case_id}: {key} must be an object")
    for key in REPOSITORY_LIST_KEYS:
        if key in target and not isinstance(target.get(key), list):
            errors.append(f"{case_id}: {key} must be a list")

    head = target.get("head")
    if head is not None:
        if not isinstance(head, dict):
            errors.append(f"{case_id}: head must be an object")
        elif head.get("type", "branch") not in {"branch", "detached", "none"}:
            errors.append(f"{case_id}: head.type must be branch, detached, or none")

    commits = target.get("commits", [])
    if isinstance(commits, list):
        seen_commit_ids: set[str] = set()
        for index, commit in enumerate(commits):
            if not isinstance(commit, dict):
                errors.append(f"{case_id}: commits[{index}] must be an object")
                continue
            commit_id = commit.get("id")
            if not isinstance(commit_id, str) or not commit_id:
                errors.append(f"{case_id}: commits[{index}].id must be a non-empty string")
            elif commit_id in seen_commit_ids:
                errors.append(f"{case_id}: duplicate commit id {commit_id!r}")
            else:
                seen_commit_ids.add(commit_id)
            for object_key in ("tree", "files", "changes"):
                if object_key in commit and not isinstance(commit.get(object_key), dict):
                    errors.append(f"{case_id}: commits[{index}].{object_key} must be an object")
            if "parents" in commit and not isinstance(commit.get("parents"), list):
                errors.append(f"{case_id}: commits[{index}].parents must be a list")

    return errors


def main() -> int:
    if OLD_TARGETS_FILE.exists():
        print(
            f"{OLD_TARGETS_FILE.relative_to(ROOT)} should not exist; "
            "generated artifacts belong under curriculum/seed_data/generated/.",
            file=sys.stderr,
        )
        return 1

    if not TARGETS_FILE.exists():
        print(f"{TARGETS_FILE.relative_to(ROOT)} is missing.", file=sys.stderr)
        return 1

    first_line = TARGETS_FILE.read_text(encoding="utf-8", errors="ignore").splitlines()[0]
    if first_line.strip() != EXPECTED_HEADER_PREFIX:
        print(
            f"{TARGETS_FILE.relative_to(ROOT)} is missing the generated-file header.",
            file=sys.stderr,
        )
        return 1

    try:
        adventure_levels, challenges, targets = _load_seed_modules()
        authored_case_ids = _collect_case_ids(adventure_levels, challenges)
    except Exception as exc:  # noqa: BLE001 - CI guard should print actionable failures.
        print(f"Could not load seed data: {exc}", file=sys.stderr)
        return 1

    generated_case_ids = set(targets)
    missing = sorted(authored_case_ids - generated_case_ids)
    extra = sorted(generated_case_ids - authored_case_ids)
    errors: list[str] = []

    if missing:
        errors.append(f"missing generated target(s): {', '.join(missing[:20])}")
    if extra:
        errors.append(f"generated target(s) without authored variant: {', '.join(extra[:20])}")

    for case_id in sorted(generated_case_ids & authored_case_ids):
        errors.extend(_validate_target_shape(case_id, targets[case_id]))

    if errors:
        print("Generated curriculum target problems found:", file=sys.stderr)
        for error in errors[:80]:
            print(f"  {error}", file=sys.stderr)
        if len(errors) > 80:
            print(f"  ... {len(errors) - 80} more", file=sys.stderr)
        print("\nRun `cd backend && python manage.py generate_targets` after changing solutions.", file=sys.stderr)
        return 1

    print(f"Generated curriculum targets are consistent ({len(authored_case_ids)} cases).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
