# Generated by Django 6.0.5 on 2026-06-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('required_successful_attempts', models.PositiveIntegerField(default=3)),
                ('min_counted_commands', models.PositiveIntegerField(default=1)),
                ('max_counted_commands', models.PositiveIntegerField(default=4)),
                ('is_required', models.BooleanField(default=True)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('scenario_context', models.JSONField(blank=True, default=dict)),
                ('objective_checks', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('encounter_spec', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['command_form__command_skill__sort_order', 'command_form__sort_order', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AdventureLevelAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=16)),
                ('correctness_score', models.PositiveIntegerField(default=0)),
                ('efficiency_score', models.PositiveIntegerField(default=0)),
                ('independence_score', models.PositiveIntegerField(default=0)),
                ('final_score', models.PositiveIntegerField(default=0)),
                ('mastery_gain', models.FloatField(default=0.0)),
                ('hint_count', models.PositiveIntegerField(default=0)),
                ('command_count', models.PositiveIntegerField(default=0)),
                ('counted_command_count', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('repository_state', models.JSONField(blank=True, default=dict)),
                ('battle_state', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['run_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdventureMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.PositiveIntegerField(default=0)),
                ('introduced', models.BooleanField(default=False)),
                ('last_seen_seq', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdventureRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='started', max_length=16)),
                ('mode', models.CharField(choices=[('primary', 'Primary'), ('replay', 'Replay')], default='primary', max_length=16)),
                ('current_level_index', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('session_score', models.PositiveIntegerField(default=0)),
                ('mastery_progress_gained', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('passed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdventureVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=80)),
                ('initial_state', models.JSONField(default=dict)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('target_state', models.JSONField(blank=True, default=dict)),
                ('solution_commands', models.JSONField(blank=True, default=list)),
                ('case_id', models.CharField(blank=True, max_length=160)),
                ('semantic_key', models.CharField(blank=True, max_length=240)),
                ('parameter_context', models.JSONField(blank=True, default=dict)),
                ('scenario_context', models.JSONField(blank=True, default=dict)),
                ('hint_set', models.JSONField(blank=True, default=list)),
                ('scaffold_policy', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['adventure_level_id', 'semantic_key', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommandAdventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('pass_bar_fraction', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
