# Generated by Django 6.0.5 on 2026-06-17 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0001_initial'),
        ('authoring', '0001_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurelevel',
            name='command_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_levels', to='curriculum.commandform'),
        ),
        migrations.AddField(
            model_name='adventurelevel',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='adventures.adventurelevel'),
        ),
        migrations.AddField(
            model_name='adventurelevelattempt',
            name='adventure_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='adventures.adventurelevel'),
        ),
        migrations.AddField(
            model_name='adventuremastery',
            name='adventure_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_states', to='adventures.adventurelevel'),
        ),
        migrations.AddField(
            model_name='adventuremastery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adventurerun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adventurelevelattempt',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='adventures.adventurerun'),
        ),
        migrations.AddField(
            model_name='adventurevariant',
            name='adventure_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_variants', to='adventures.adventurelevel'),
        ),
        migrations.AddField(
            model_name='adventurelevelattempt',
            name='selected_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='adventures.adventurevariant'),
        ),
        migrations.AddField(
            model_name='commandadventure',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_adventures', to='curriculum.chapter'),
        ),
        migrations.AddField(
            model_name='commandadventure',
            name='source_content_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_command_adventures', to='authoring.contentdefinition'),
        ),
        migrations.AddField(
            model_name='adventurerun',
            name='command_adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='adventures.commandadventure'),
        ),
        migrations.AddField(
            model_name='adventurelevel',
            name='command_adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='adventures.commandadventure'),
        ),
        migrations.AddIndex(
            model_name='adventuremastery',
            index=models.Index(fields=['user', 'adventure_level'], name='advmastery_user_level_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adventuremastery',
            unique_together={('user', 'adventure_level')},
        ),
        migrations.AddIndex(
            model_name='adventurelevelattempt',
            index=models.Index(fields=['run', 'order'], name='advattempt_run_order_idx'),
        ),
        migrations.AddIndex(
            model_name='adventurerun',
            index=models.Index(fields=['user', 'command_adventure', 'status'], name='advrun_user_adv_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adventurelevel',
            unique_together={('command_form', 'slug')},
        ),
    ]
