# Generated by Django 6.0.5 on 2026-06-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_rename_module_storey_and_more'),
        ('curriculum', '0004_alter_commandform_options_alter_commandskill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adventurequest',
            options={'ordering': ['command_form__command_skill__sort_order', 'command_form__sort_order', 'sort_order']},
        ),
        migrations.AlterField(
            model_name='adventurequest',
            name='command_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_quests', to='curriculum.commandform'),
        ),
        migrations.AlterField(
            model_name='adventurevariant',
            name='adventure_quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_variants', to='adventures.adventurequest'),
        ),
    ]
