# Generated by Django 6.0.5 on 2026-06-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0006_alter_adventurequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurequest',
            name='encounter_spec',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adventurequestattempt',
            name='battle_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
