# Generated by Django 6.0.5 on 2026-06-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0008_rename_quest_to_level'),
        ('authoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandadventure',
            name='source_content_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_command_adventures', to='authoring.contentdefinition'),
        ),
    ]
