COMMAND_TOPICS = [
    {
        "module": "creating-inspecting-repositories",
        "slug": "git-init",
        "base_command": "git init",
        "title": "git init",
        "summary": "Create Git metadata in the current directory or a named directory.",
        "usages": [
            {"slug": "current-directory", "usage_form": "git init", "label": "Initialize the current folder"},
            {"slug": "named-directory", "usage_form": "git init <directory>", "label": "Initialize a named folder"},
        ],
    },
    {
        "module": "creating-inspecting-repositories",
        "slug": "git-clone",
        "base_command": "git clone",
        "title": "git clone",
        "summary": "Create a local repository from a remote URL.",
        "usages": [
            {"slug": "default-folder", "usage_form": "git clone <url>", "label": "Clone into the default folder"},
            {"slug": "named-folder", "usage_form": "git clone <url> <folder>", "label": "Clone into a named folder"},
        ],
    },
    {
        "module": "creating-inspecting-repositories",
        "slug": "git-status",
        "base_command": "git status",
        "title": "git status",
        "summary": "Inspect branch, staging, working directory, and conflict state.",
        "usages": [
            {"slug": "short-status", "usage_form": "git status", "label": "Read repository status"},
            {"slug": "ignored", "usage_form": "git status --ignored", "label": "Include ignored files"},
        ],
    },
    {
        "module": "creating-inspecting-repositories",
        "slug": "git-log",
        "base_command": "git log",
        "title": "git log",
        "summary": "Inspect commit history.",
        "usages": [
            {"slug": "oneline", "usage_form": "git log --oneline", "label": "Compact history"},
            {"slug": "graph-all", "usage_form": "git log --oneline --graph --all", "label": "Graph all refs"},
        ],
    },
    {
        "module": "creating-inspecting-repositories",
        "slug": "git-show",
        "base_command": "git show",
        "title": "git show",
        "summary": "Inspect a commit or object.",
        "usages": [
            {"slug": "head", "usage_form": "git show", "label": "Inspect HEAD"},
            {"slug": "commit", "usage_form": "git show <commit>", "label": "Inspect a named commit"},
        ],
    },
    {
        "module": "tracking-changes-snapshots",
        "slug": "git-add",
        "base_command": "git add",
        "title": "git add",
        "summary": "Copy selected working directory changes into the staging area.",
        "usages": [
            {"slug": "file", "usage_form": "git add <file>", "label": "Stage one file"},
            {"slug": "dot", "usage_form": "git add .", "label": "Stage visible changes below the current folder"},
            {"slug": "all", "usage_form": "git add -A", "label": "Stage all changes"},
            {"slug": "patch", "usage_form": "git add -p", "label": "Stage selected hunks"},
        ],
    },
    {
        "module": "tracking-changes-snapshots",
        "slug": "git-diff",
        "base_command": "git diff",
        "title": "git diff",
        "summary": "Compare working directory, staging area, and committed states.",
        "usages": [
            {"slug": "working", "usage_form": "git diff", "label": "Inspect unstaged changes"},
            {"slug": "staged", "usage_form": "git diff --staged", "label": "Inspect staged changes"},
        ],
    },
    {
        "module": "tracking-changes-snapshots",
        "slug": "git-commit",
        "base_command": "git commit",
        "title": "git commit",
        "summary": "Create a commit from the staged snapshot.",
        "usages": [
            {"slug": "message", "usage_form": "git commit -m <message>", "label": "Commit with a message"},
            {"slug": "amend", "usage_form": "git commit --amend", "label": "Replace the latest local commit"},
        ],
    },
    {
        "module": "tracking-changes-snapshots",
        "slug": "git-rm",
        "base_command": "git rm",
        "title": "git rm",
        "summary": "Remove tracked files from the working directory and index.",
        "usages": [
            {"slug": "tracked-file", "usage_form": "git rm <file>", "label": "Remove a tracked file"},
            {"slug": "cached", "usage_form": "git rm --cached <file>", "label": "Stop tracking but keep local file"},
        ],
    },
    {
        "module": "tracking-changes-snapshots",
        "slug": "git-restore",
        "base_command": "git restore",
        "title": "git restore",
        "summary": "Restore working directory or staging area contents.",
        "usages": [
            {"slug": "working-file", "usage_form": "git restore <file>", "label": "Discard a working-tree change"},
            {"slug": "staged-file", "usage_form": "git restore --staged <file>", "label": "Unstage a file"},
        ],
    },
    {
        "module": "branching-switching",
        "slug": "git-branch",
        "base_command": "git branch",
        "title": "git branch",
        "summary": "List, create, move, or delete branch pointers.",
        "usages": [
            {"slug": "list", "usage_form": "git branch", "label": "List local branches"},
            {"slug": "create", "usage_form": "git branch <name>", "label": "Create a branch pointer"},
            {"slug": "delete", "usage_form": "git branch -d <name>", "label": "Delete a branch pointer"},
        ],
    },
    {
        "module": "branching-switching",
        "slug": "git-switch",
        "base_command": "git switch",
        "title": "git switch",
        "summary": "Move HEAD to another branch or create-and-switch.",
        "usages": [
            {"slug": "existing", "usage_form": "git switch <branch>", "label": "Switch to an existing branch"},
            {"slug": "create", "usage_form": "git switch -c <branch>", "label": "Create and switch"},
        ],
    },
    {
        "module": "branching-switching",
        "slug": "git-checkout",
        "base_command": "git checkout",
        "title": "git checkout",
        "summary": "Use checkout only where older Git spelling is still necessary.",
        "usages": [
            {"slug": "legacy-create", "usage_form": "git checkout -b <branch>", "label": "Legacy create-and-switch spelling"},
        ],
    },
    {
        "module": "merging-conflicts",
        "slug": "git-merge",
        "base_command": "git merge",
        "title": "git merge",
        "summary": "Combine another branch into the current branch.",
        "usages": [
            {"slug": "fast-forward", "usage_form": "git merge <branch>", "label": "Merge a branch"},
            {"slug": "abort", "usage_form": "git merge --abort", "label": "Abort a conflicted merge"},
        ],
    },
    {
        "module": "undoing-recovery",
        "slug": "git-reset",
        "base_command": "git reset",
        "title": "git reset",
        "summary": "Move refs and optionally reset index or working tree.",
        "usages": [
            {"slug": "soft", "usage_form": "git reset --soft <commit>", "label": "Move branch, keep staged changes"},
            {"slug": "mixed", "usage_form": "git reset <commit>", "label": "Move branch and unstage changes"},
            {"slug": "hard", "usage_form": "git reset --hard <commit>", "label": "Move branch and reset files"},
        ],
    },
    {
        "module": "undoing-recovery",
        "slug": "git-revert",
        "base_command": "git revert",
        "title": "git revert",
        "summary": "Create a new commit that reverses an existing commit.",
        "usages": [
            {"slug": "one-commit", "usage_form": "git revert <commit>", "label": "Revert one commit"},
        ],
    },
    {
        "module": "undoing-recovery",
        "slug": "git-reflog",
        "base_command": "git reflog",
        "title": "git reflog",
        "summary": "Inspect recent HEAD movements when supported by the simulator.",
        "usages": [
            {"slug": "head", "usage_form": "git reflog", "label": "Inspect HEAD movements"},
        ],
    },
    {
        "module": "temporary-work-patches",
        "slug": "git-stash",
        "base_command": "git stash",
        "title": "git stash",
        "summary": "Temporarily shelve work and restore it later.",
        "usages": [
            {"slug": "push", "usage_form": "git stash", "label": "Push work to the stash"},
            {"slug": "pop", "usage_form": "git stash pop", "label": "Restore and remove the top stash"},
        ],
    },
    {
        "module": "temporary-work-patches",
        "slug": "git-cherry-pick",
        "base_command": "git cherry-pick",
        "title": "git cherry-pick",
        "summary": "Apply one existing commit onto the current branch.",
        "usages": [
            {"slug": "one-commit", "usage_form": "git cherry-pick <commit>", "label": "Apply one commit"},
        ],
    },
    {
        "module": "remotes-collaboration",
        "slug": "git-remote",
        "base_command": "git remote",
        "title": "git remote",
        "summary": "List and manage remote names and URLs.",
        "usages": [
            {"slug": "list", "usage_form": "git remote -v", "label": "List remote URLs"},
            {"slug": "add", "usage_form": "git remote add <name> <url>", "label": "Add a remote"},
        ],
    },
    {
        "module": "remotes-collaboration",
        "slug": "git-fetch",
        "base_command": "git fetch",
        "title": "git fetch",
        "summary": "Update remote-tracking branches without changing local work.",
        "usages": [
            {"slug": "origin", "usage_form": "git fetch origin", "label": "Fetch a remote"},
            {"slug": "prune", "usage_form": "git fetch --prune", "label": "Prune stale tracking refs"},
        ],
    },
    {
        "module": "remotes-collaboration",
        "slug": "git-pull",
        "base_command": "git pull",
        "title": "git pull",
        "summary": "Fetch and integrate upstream changes.",
        "usages": [
            {"slug": "default", "usage_form": "git pull", "label": "Pull the configured upstream"},
            {"slug": "rebase", "usage_form": "git pull --rebase", "label": "Pull with rebase"},
        ],
    },
    {
        "module": "remotes-collaboration",
        "slug": "git-push",
        "base_command": "git push",
        "title": "git push",
        "summary": "Publish local commits or delete remote branches.",
        "usages": [
            {"slug": "upstream", "usage_form": "git push -u origin <branch>", "label": "Push and set upstream"},
            {"slug": "delete", "usage_form": "git push origin --delete <branch>", "label": "Delete a remote branch"},
        ],
    },
]
