"""Regenerate ``curriculum/seed_data/generated/generated_targets.py``.

The git command engine lives in the frontend now, so target repository states are
no longer derived in Python. This command collects every seed variant's
``initial_state`` + ``solution_commands`` (+ mid-sequence workspace file edits),
replays each through the real browser engine via a small Vite-driven Node script
(``frontend/scripts/generate-targets.mjs``), verifies that every command is
processable within the level budget, and writes the results back as
``TARGET_STATES``. The same replay is fingerprinted into
``SOLUTION_TRAJECTORIES`` (``generated/generated_trajectories.py``), which lets
the runtime tutor tell which solution step a learner's repository is at.

Run after changing any variant's initial state or solution:

    python manage.py generate_targets
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from curriculum.management.commands.seed_legacy_modules import LEGACY_MODULE_LEVELS
from curriculum.seed_data.adventure_levels import ADVENTURE_LEVELS
from curriculum.seed_data.challenges import CHALLENGES
from simulator.trajectory import build_solution_trajectory

# generate_targets.py -> commands -> management -> curriculum -> backend -> repo
REPO_ROOT = Path(__file__).resolve().parents[4]
FRONTEND_DIR = REPO_ROOT / "frontend"
GENERATOR_SCRIPT = FRONTEND_DIR / "scripts" / "generate-targets.mjs"
GENERATED_DIR = Path(__file__).resolve().parents[2] / "seed_data" / "generated"
TARGETS_FILE = GENERATED_DIR / "generated_targets.py"
TRAJECTORIES_FILE = GENERATED_DIR / "generated_trajectories.py"

HEADER = (
    "# Generated by `python manage.py generate_targets`. Do not edit by hand.\n"
    "# Regenerate after changing any variant's initial_state or solution_commands.\n"
    "import json\n\n"
    'TARGET_STATES = json.loads(r"""\n'
)
FOOTER = '\n""")\n'
TRAJECTORY_HEADER = (
    "# Generated by `python manage.py generate_targets`. Do not edit by hand.\n"
    "# Repository fingerprints in front of every solution command; see\n"
    "# simulator/trajectory.py.\n"
    "import json\n\n"
    'SOLUTION_TRAJECTORIES = json.loads(r"""\n'
)


class Command(BaseCommand):
    help = (
        "Validate and replay every seed variant's solution through the frontend git "
        "engine to rebuild generated/generated_targets.py."
    )

    def add_arguments(self, parser) -> None:
        parser.add_argument(
            "--check",
            action="store_true",
            help=(
                "Fail (non-zero) if regeneration would change generated/generated_targets.py, "
                "instead of writing it."
            ),
        )

    def handle(self, *args, **options) -> None:
        cases = self._collect_cases()
        self.stdout.write(f"Collected {len(cases)} variant solutions.")
        targets, replays = self._run_generator(cases)
        missing = sorted(set(cases) - set(targets))
        if missing:
            raise CommandError(f"Generator returned no target for: {', '.join(missing[:10])}")
        trajectories = {
            case_id: build_solution_trajectory(replay) for case_id, replay in replays.items()
        }

        outputs = [
            (TARGETS_FILE, self._render(targets, HEADER), f"{len(targets)} target states"),
            (
                TRAJECTORIES_FILE,
                self._render(trajectories, TRAJECTORY_HEADER),
                f"{len(trajectories)} solution trajectories",
            ),
        ]
        if options["check"]:
            for path, rendered, _ in outputs:
                current = path.read_text(encoding="utf-8") if path.exists() else ""
                if current != rendered:
                    raise CommandError(
                        f"generated/{path.name} is stale - run `python manage.py generate_targets`."
                    )
            self.stdout.write(self.style.SUCCESS("Generated targets and trajectories are up to date."))
            return

        for path, rendered, summary in outputs:
            path.write_text(rendered, encoding="utf-8")
            relative = path.relative_to(Path(__file__).resolve().parents[2])
            self.stdout.write(self.style.SUCCESS(f"Wrote {summary} to {relative}."))

    def _collect_cases(self) -> dict[str, dict]:
        cases: dict[str, dict] = {}

        def add(variant: dict, *, max_counted_commands: int) -> None:
            case_id = variant.get("case_id")
            if not case_id:
                return
            if case_id in cases:
                raise CommandError(f"Duplicate variant case_id: {case_id!r}")
            cases[case_id] = {
                "initial_state": variant.get("initial_state_template") or {},
                "solution_commands": list(variant.get("solution_commands_template") or []),
                "workspace_files": list(variant.get("solution_workspace_files_template") or []),
                "max_counted_commands": max_counted_commands,
            }

        for spec in ADVENTURE_LEVELS:
            for variant in spec.get("variants", []):
                add(
                    variant,
                    max_counted_commands=spec.get("max_counted_commands") or 0,
                )
        for challenge in CHALLENGES:
            for level in challenge.get("levels", []):
                for variant in level.get("variants", []):
                    add(
                        variant,
                        max_counted_commands=level.get("max_counted_commands") or 0,
                    )
        # Legacy module tiers author their cases inline (no *_template suffix)
        # rather than through the variant-spec helpers, so normalize the two
        # key names the collector reads.
        for level in LEGACY_MODULE_LEVELS:
            for tier in level.get("tiers", {}).values():
                for case in tier.get("cases", []):
                    add(
                        {
                            "case_id": case.get("case_id"),
                            "initial_state_template": case.get("initial_state") or {},
                            "solution_commands_template": case.get("solution_commands") or [],
                            "solution_workspace_files_template": case.get(
                                "solution_workspace_files"
                            )
                            or [],
                        },
                        max_counted_commands=tier.get("max_counted_commands") or 0,
                    )
        return cases

    def _run_generator(self, cases: dict[str, dict]) -> tuple[dict[str, dict], dict[str, dict]]:
        if not GENERATOR_SCRIPT.exists():
            raise CommandError(f"Generator script not found: {GENERATOR_SCRIPT}")
        with tempfile.TemporaryDirectory() as tmp:
            input_path = Path(tmp) / "cases.json"
            output_path = Path(tmp) / "targets.json"
            input_path.write_text(json.dumps(cases), encoding="utf-8")
            try:
                result = subprocess.run(
                    ["node", str(GENERATOR_SCRIPT), str(input_path), str(output_path)],
                    cwd=FRONTEND_DIR,
                    capture_output=True,
                    text=True,
                )
            except FileNotFoundError as exc:
                raise CommandError(
                    "`node` was not found on PATH - install Node to run the generator."
                ) from exc
            if result.returncode != 0:
                raise CommandError(f"Target generator failed:\n{result.stderr or result.stdout}")
            output = json.loads(output_path.read_text(encoding="utf-8"))
            return output["targets"], output["replays"]

    def _render(self, data: dict[str, dict], header: str) -> str:
        body = json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False)
        # The payload is embedded in a raw triple-quoted string; valid JSON can
        # never contain `"""`, but guard anyway so a bad payload fails loudly.
        if '"""' in body:
            raise CommandError(
                "Generated JSON contains a triple-quote and cannot be embedded safely."
            )
        return f"{header}{body}{FOOTER}"
