"""Regenerate ``curriculum/seed_data/generated/generated_targets.py``.

The git command engine lives in the frontend now, so target repository states are
no longer derived in Python. This command collects every seed variant's
``initial_state`` + ``solution_commands`` (+ mid-sequence workspace file edits),
replays each through the real browser engine via a small Vite-driven Node script
(``frontend/scripts/generate-targets.mjs``), and writes the results back as
``TARGET_STATES``.

Run after changing any variant's initial state or solution:

    python manage.py generate_targets
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from curriculum.seed_data.adventure_levels import ADVENTURE_LEVELS
from curriculum.seed_data.challenges import CHALLENGES

# generate_targets.py -> commands -> management -> curriculum -> backend -> repo
REPO_ROOT = Path(__file__).resolve().parents[4]
FRONTEND_DIR = REPO_ROOT / "frontend"
GENERATOR_SCRIPT = FRONTEND_DIR / "scripts" / "generate-targets.mjs"
TARGETS_FILE = Path(__file__).resolve().parents[2] / "seed_data" / "generated" / "generated_targets.py"

HEADER = (
    "# Generated by `python manage.py generate_targets`. Do not edit by hand.\n"
    "# Regenerate after changing any variant's initial_state or solution_commands.\n"
    "import json\n\n"
    'TARGET_STATES = json.loads(r"""\n'
)
FOOTER = '\n""")\n'


class Command(BaseCommand):
    help = "Replay every seed variant's solution through the frontend git engine to rebuild generated/generated_targets.py."

    def add_arguments(self, parser) -> None:
        parser.add_argument(
            "--check",
            action="store_true",
            help=(
                "Fail (non-zero) if regeneration would change generated/generated_targets.py, "
                "instead of writing it."
            ),
        )

    def handle(self, *args, **options) -> None:
        cases = self._collect_cases()
        self.stdout.write(f"Collected {len(cases)} variant solutions.")
        targets = self._run_generator(cases)
        missing = sorted(set(cases) - set(targets))
        if missing:
            raise CommandError(f"Generator returned no target for: {', '.join(missing[:10])}")

        rendered = self._render(targets)
        if options["check"]:
            current = TARGETS_FILE.read_text(encoding="utf-8") if TARGETS_FILE.exists() else ""
            if current != rendered:
                raise CommandError(
                    "generated/generated_targets.py is stale - run `python manage.py generate_targets`."
                )
            self.stdout.write(self.style.SUCCESS("generated/generated_targets.py is up to date."))
            return

        TARGETS_FILE.write_text(rendered, encoding="utf-8")
        relative_target = TARGETS_FILE.relative_to(Path(__file__).resolve().parents[2])
        self.stdout.write(
            self.style.SUCCESS(f"Wrote {len(targets)} target states to {relative_target}.")
        )

    def _collect_cases(self) -> dict[str, dict]:
        cases: dict[str, dict] = {}

        def add(variant: dict) -> None:
            case_id = variant.get("case_id")
            if not case_id:
                return
            if case_id in cases:
                raise CommandError(f"Duplicate variant case_id: {case_id!r}")
            cases[case_id] = {
                "initial_state": variant.get("initial_state_template") or {},
                "solution_commands": list(variant.get("solution_commands_template") or []),
                "workspace_files": list(variant.get("solution_workspace_files_template") or []),
            }

        for spec in ADVENTURE_LEVELS:
            for variant in spec.get("variants", []):
                add(variant)
        for challenge in CHALLENGES:
            for level in challenge.get("levels", []):
                for variant in level.get("variants", []):
                    add(variant)
        return cases

    def _run_generator(self, cases: dict[str, dict]) -> dict[str, dict]:
        if not GENERATOR_SCRIPT.exists():
            raise CommandError(f"Generator script not found: {GENERATOR_SCRIPT}")
        with tempfile.TemporaryDirectory() as tmp:
            input_path = Path(tmp) / "cases.json"
            output_path = Path(tmp) / "targets.json"
            input_path.write_text(json.dumps(cases), encoding="utf-8")
            try:
                result = subprocess.run(
                    ["node", str(GENERATOR_SCRIPT), str(input_path), str(output_path)],
                    cwd=FRONTEND_DIR,
                    capture_output=True,
                    text=True,
                )
            except FileNotFoundError as exc:
                raise CommandError("`node` was not found on PATH - install Node to run the generator.") from exc
            if result.returncode != 0:
                raise CommandError(f"Target generator failed:\n{result.stderr or result.stdout}")
            return json.loads(output_path.read_text(encoding="utf-8"))

    def _render(self, targets: dict[str, dict]) -> str:
        body = json.dumps(targets, indent=2, sort_keys=True, ensure_ascii=False)
        # The payload is embedded in a raw triple-quoted string; valid JSON can
        # never contain `"""`, but guard anyway so a bad payload fails loudly.
        if '"""' in body:
            raise CommandError("Generated JSON contains a triple-quote and cannot be embedded safely.")
        return f"{HEADER}{body}{FOOTER}"
