# Generated by Django 6.0.7 on 2026-07-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('brief', models.TextField(blank=True)),
                ('narrative_brief', models.JSONField(blank=True, default=dict)),
                ('level_type', models.CharField(choices=[('command_introduction', 'Command introduction'), ('guided_workflow', 'Guided workflow'), ('applied_scenario', 'Applied scenario'), ('mastery_incident', 'Mastery incident')], default='guided_workflow', max_length=32)),
                ('is_required', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['chapter__sort_order', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdventureRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='started', max_length=16)),
                ('is_replay', models.BooleanField(default=False)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('library_opened', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('passed_at', models.DateTimeField(blank=True, null=True)),
                ('command_count', models.PositiveIntegerField(default=0)),
                ('counted_command_count', models.PositiveIntegerField(default=0)),
                ('repository_state', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AdventureRunWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=16)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('counted_command_count', models.PositiveIntegerField(default=0)),
                ('command_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['run_id', 'wave__sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdventureWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('story', models.TextField(blank=True)),
                ('task', models.TextField(blank=True)),
                ('min_counted_commands', models.PositiveIntegerField(default=1)),
                ('max_counted_commands', models.PositiveIntegerField(default=4)),
                ('objective_checks', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdventureWaveVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=80)),
                ('initial_state', models.JSONField(default=dict)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('target_state', models.JSONField(blank=True, default=dict)),
                ('solution_commands', models.JSONField(blank=True, default=list)),
                ('case_id', models.CharField(blank=True, max_length=160)),
                ('semantic_key', models.CharField(blank=True, max_length=240)),
                ('parameter_context', models.JSONField(blank=True, default=dict)),
                ('scenario_context', models.JSONField(blank=True, default=dict)),
                ('scaffold_policy', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['wave_id', 'semantic_key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_at', models.DateTimeField(blank=True, null=True)),
                ('solves', models.PositiveIntegerField(default=0)),
                ('mastered', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
