# Generated by Django 6.0.5 on 2026-06-07 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('required_successful_attempts', models.PositiveIntegerField(default=3)),
                ('min_counted_commands', models.PositiveIntegerField(default=1)),
                ('max_counted_commands', models.PositiveIntegerField(default=4)),
                ('is_required', models.BooleanField(default=True)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('scenario_context', models.JSONField(blank=True, default=dict)),
                ('objective_checks', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='curriculum.commandform')),
            ],
            options={
                'ordering': ['usage__topic__sort_order', 'usage__sort_order', 'sort_order'],
                'unique_together': {('usage', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='AdventureVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=80)),
                ('initial_state', models.JSONField(default=dict)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('target_state', models.JSONField(blank=True, default=dict)),
                ('solution_commands', models.JSONField(blank=True, default=list)),
                ('case_id', models.CharField(blank=True, max_length=160)),
                ('semantic_key', models.CharField(blank=True, max_length=240)),
                ('parameter_context', models.JSONField(blank=True, default=dict)),
                ('scenario_context', models.JSONField(blank=True, default=dict)),
                ('hint_set', models.JSONField(blank=True, default=list)),
                ('scaffold_policy', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('adventure_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='adventures.adventureproblem')),
            ],
            options={
                'ordering': ['adventure_problem_id', 'semantic_key', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommandAdventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='command_adventure', to='curriculum.storey')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdventureRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='started', max_length=16)),
                ('current_problem_index', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('mastery_progress_gained', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('command_adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='adventures.commandadventure')),
            ],
        ),
        migrations.CreateModel(
            name='AdventureProblemAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=16)),
                ('correctness_score', models.PositiveIntegerField(default=0)),
                ('efficiency_score', models.PositiveIntegerField(default=0)),
                ('independence_score', models.PositiveIntegerField(default=0)),
                ('final_score', models.PositiveIntegerField(default=0)),
                ('mastery_gain', models.FloatField(default=0.0)),
                ('hint_count', models.PositiveIntegerField(default=0)),
                ('command_count', models.PositiveIntegerField(default=0)),
                ('counted_command_count', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('repository_state', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('adventure_problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='adventures.adventureproblem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='adventures.adventurerun')),
                ('selected_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='adventures.adventurevariant')),
            ],
            options={
                'ordering': ['run_id', 'order', 'id'],
                'indexes': [models.Index(fields=['run', 'order'], name='advattempt_run_order_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='adventurerun',
            index=models.Index(fields=['user', 'command_adventure', 'status'], name='advrun_user_adv_status_idx'),
        ),
    ]
