# Generated by Django 6.0.7 on 2026-07-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0001_initial'),
        ('authoring', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurelevel',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_levels', to='curriculum.chapter'),
        ),
        migrations.AddField(
            model_name='adventurelevel',
            name='command_forms',
            field=models.ManyToManyField(blank=True, related_name='adventure_levels', to='curriculum.commandform'),
        ),
        migrations.AddField(
            model_name='adventurelevel',
            name='source_content_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_adventure_levels', to='authoring.contentdefinition'),
        ),
        migrations.AddField(
            model_name='adventurerun',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='adventures.adventurelevel'),
        ),
        migrations.AddField(
            model_name='adventurerun',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_runs', to='players.player'),
        ),
        migrations.AddField(
            model_name='adventurerunwave',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_waves', to='adventures.adventurerun'),
        ),
        migrations.AddField(
            model_name='adventurewave',
            name='command_forms',
            field=models.ManyToManyField(blank=True, related_name='adventure_waves', to='curriculum.commandform'),
        ),
        migrations.AddField(
            model_name='adventurewave',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='adventures.adventurelevel'),
        ),
        migrations.AddField(
            model_name='adventurerunwave',
            name='wave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_waves', to='adventures.adventurewave'),
        ),
        migrations.AddField(
            model_name='adventurerun',
            name='current_wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_runs', to='adventures.adventurewave'),
        ),
        migrations.AddField(
            model_name='adventurewavevariant',
            name='wave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='adventures.adventurewave'),
        ),
        migrations.AddField(
            model_name='adventurerunwave',
            name='selected_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_waves', to='adventures.adventurewavevariant'),
        ),
        migrations.AddField(
            model_name='adventurerun',
            name='selected_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='adventures.adventurewavevariant'),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='command_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mastery_states', to='curriculum.commandform'),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mastery_states', to='players.player'),
        ),
        migrations.AddIndex(
            model_name='adventurelevel',
            index=models.Index(fields=['chapter', 'sort_order'], name='adv_level_chapter_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='adventurelevel',
            constraint=models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_adventure_level_chapter_slug'),
        ),
        migrations.AddIndex(
            model_name='adventurewave',
            index=models.Index(fields=['level', 'sort_order'], name='adv_wave_slot_idx'),
        ),
        migrations.AddConstraint(
            model_name='adventurewave',
            constraint=models.UniqueConstraint(fields=('level', 'slug'), name='unique_adventure_wave_slug'),
        ),
        migrations.AddConstraint(
            model_name='adventurewavevariant',
            constraint=models.UniqueConstraint(fields=('wave', 'slug'), name='unique_adventure_wave_variant_slug'),
        ),
        migrations.AddConstraint(
            model_name='adventurerunwave',
            constraint=models.UniqueConstraint(fields=('run', 'wave'), name='unique_adventure_run_wave'),
        ),
        migrations.AddIndex(
            model_name='adventurerun',
            index=models.Index(fields=['player', 'level', 'status'], name='advrun_plyr_level_status_idx'),
        ),
        migrations.AddIndex(
            model_name='adventurerun',
            index=models.Index(fields=['player', 'status'], name='advrun_plyr_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='adventurerun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'started')), fields=('player', 'level'), name='unique_active_adventure_run'),
        ),
        migrations.AddIndex(
            model_name='skillmastery',
            index=models.Index(fields=['player', 'command_form'], name='skillmastery_plyr_form_idx'),
        ),
        migrations.AddConstraint(
            model_name='skillmastery',
            constraint=models.UniqueConstraint(fields=('player', 'command_form'), name='unique_skill_mastery_player_form'),
        ),
    ]
