# Generated by Django 6.0.5 on 2026-06-09 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureproblem',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='adventures.adventureproblem'),
        ),
        migrations.AddField(
            model_name='adventurerun',
            name='passed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventurerun',
            name='session_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandadventure',
            name='pass_bar_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdventureMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.PositiveIntegerField(default=0)),
                ('introduced', models.BooleanField(default=False)),
                ('last_seen_seq', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_states', to='adventures.adventureproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'adventure_problem'], name='advmastery_user_problem_idx')],
                'unique_together': {('user', 'adventure_problem')},
            },
        ),
    ]
