# Generated by Django 6.0.5 on 2026-06-10 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_adventurerun_mode'),
        ('curriculum', '0002_storey_chest_rewards'),
        ('practice', '0001_initial'),
        ('progress', '0002_wallet_cointransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdventureProblem',
            new_name='AdventureQuest',
        ),
        migrations.RenameModel(
            old_name='AdventureProblemAttempt',
            new_name='AdventureQuestAttempt',
        ),
        migrations.AlterModelOptions(
            name='adventurevariant',
            options={'ordering': ['adventure_quest_id', 'semantic_key', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='adventuremastery',
            name='advmastery_user_problem_idx',
        ),
        migrations.RenameField(
            model_name='adventuremastery',
            old_name='adventure_problem',
            new_name='adventure_quest',
        ),
        migrations.RenameField(
            model_name='adventurequestattempt',
            old_name='adventure_problem',
            new_name='adventure_quest',
        ),
        migrations.RenameField(
            model_name='adventurevariant',
            old_name='adventure_problem',
            new_name='adventure_quest',
        ),
        migrations.AlterUniqueTogether(
            name='adventuremastery',
            unique_together={('user', 'adventure_quest')},
        ),
        migrations.AddIndex(
            model_name='adventuremastery',
            index=models.Index(fields=['user', 'adventure_quest'], name='advmastery_user_problem_idx'),
        ),
    ]
