# Generated by Django 6.0.5 on 2026-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_remove_unused_level_metadata'),
        ('curriculum', '0002_remove_unused_narrative_briefs'),
        ('players', '0002_remove_playerpreferences_theme_mode'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='skillmastery',
            name='skillmastery_plyr_form_idx',
        ),
        migrations.AddConstraint(
            model_name='adventurerun',
            constraint=models.CheckConstraint(condition=models.Q(('stars__lte', 3)), name='adventure_run_stars_lte_3'),
        ),
        migrations.AddConstraint(
            model_name='adventurerunwave',
            constraint=models.CheckConstraint(condition=models.Q(('stars__lte', 3)), name='adventure_run_wave_stars_lte_3'),
        ),
        migrations.AddConstraint(
            model_name='adventurewave',
            constraint=models.CheckConstraint(condition=models.Q(('min_counted_commands__gte', 0), ('max_counted_commands__gte', models.F('min_counted_commands'))), name='adventure_wave_valid_command_budget'),
        ),
    ]
