# Generated by Django 6.0.7 on 2026-07-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_remove_skillmastery_skillmastery_plyr_form_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurewavevariant',
            name='slug',
            field=models.SlugField(max_length=160),
        ),
    ]
