# Generated by Django 6.0.5 on 2026-09-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0008_adventureleveltierrun_changed_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventureleveltierwavevariant',
            name='scaffold_policy',
        ),
        migrations.RemoveField(
            model_name='adventurewavevariant',
            name='scaffold_policy',
        ),
    ]
